<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { Delete, Plus, Select } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import ImageUpload from './ImageUpload.vue'

const props=defineProps<{centerKey:string;record:Record<string,any>;activeTab:string;showPrice?:boolean}>()
const emit=defineEmits<{save:[value:any];cancel:[]}>()
const draft=reactive<any>({}),products=ref<any[]>([]),saving=ref(false)
const clone=(value:any)=>JSON.parse(JSON.stringify(value??null))
const row=(values:any={})=>({name:'',description:'',value:'',unit:'',group:'',condition:'',source:'',title:'',image:'',...values})
function reset(){Object.keys(draft).forEach(key=>delete draft[key]);Object.assign(draft,clone(props.record));if(['software','algorithms'].includes(props.centerKey)&&!draft.commercial)draft.commercial={materialCode:'',unit:'套',isAgentProduct:false,agentPrice:null,salePrice:null,warrantyMonths:12,extendedWarrantyRule:'',applicableScenes:[],salesNotes:'',commercialStatus:'ACTIVE',licenseUnit:'',includedQuantity:null,overageUnitPrice:null,deliveryMethod:''};if(props.centerKey==='solutions')loadProducts()}
async function loadProducts(){if(products.value.length)return;const response=await fetch('/api/products',{headers:{Authorization:'Bearer '+localStorage.hzToken}});if(response.ok)products.value=await response.json()}
watch(()=>[props.centerKey,props.record.id],reset,{immediate:true})
const title=computed(()=>({software:'软件','algorithms':'算法','model-capabilities':'模型能力',scenes:'场景',solutions:'方案'} as any)[props.centerKey])
function normalize(list:any[]=[]){return list.map((item,index)=>{const {id,...editable}=item;return {...editable,sortOrder:index}})}
function payload(){
 const base={name:draft.name,code:draft.code||'',version:draft.version||'v1.0',category:draft.category||'通用',status:draft.status,summary:draft.summary||''}
 if(props.centerKey==='software')return {...base,description:draft.description||'',logo:draft.logo||'',softwareType:draft.softwareType||'PLATFORM',vendor:draft.vendor||'',deploymentMode:draft.deploymentMode||'PRIVATE',supportedOs:draft.supportedOs||[],databases:draft.databases||[],protocols:draft.protocols||[],boundaries:draft.boundaries||[],modules:normalize(draft.modules||[]).map((item:any)=>({...item,features:normalize(item.features||[])})),versions:(draft.versions||[]).map((item:any)=>{const {id,...editable}=item;return editable}),screenshots:normalize(draft.screenshots||[])}
 if(props.centerKey==='algorithms')return {...base,principle:draft.principle||'',inputSummary:draft.inputSummary||'',outputSummary:draft.outputSummary||'',parameters:normalize(draft.parameters||[]),metrics:normalize(draft.metrics||[]),boundaries:draft.boundaries||[]}
 if(props.centerKey==='model-capabilities')return {...base,modelType:draft.modelType||'DETECTION',taskType:draft.taskType||'',functionType:draft.functionType||'',metrics:normalize(draft.metrics||[]),inputDefinitions:normalize(draft.inputDefinitions||[]),outputDefinitions:normalize(draft.outputDefinitions||[]),deploymentRequirements:draft.deploymentRequirements||{},useConditions:draft.useConditions||[],boundaries:draft.boundaries||[]}
 if(props.centerKey==='scenes')return {name:draft.name,category:draft.category||'水域安全',summary:draft.summary||'',coverImage:draft.coverImage||'',status:draft.status,tags:draft.tags||[],conditions:draft.conditions||[],painPoints:normalize(draft.painPoints||[]),goals:normalize(draft.goals||[]),process:normalize(draft.process||[]),coreCapabilitySummary:draft.coreCapabilitySummary||''}
 return {...base,sceneId:draft.sceneId,tier:draft.tier||'STANDARD',coverImage:draft.coverImage||'',targetDescription:draft.targetDescription||'',coverageScope:draft.coverageScope||'',implementationNotes:draft.implementationNotes||'',architecture:normalize(draft.architecture||[]),capabilityCoverage:normalize(draft.capabilityCoverage||[])}
}
async function save(){saving.value=true;try{const commercial=draft.commercial?{...draft.commercial,applicableScenes:Array.isArray(draft.commercial.applicableScenes)?draft.commercial.applicableScenes:String(draft.commercial.applicableScenes||'').split(/[、,，\n]/).map((x:string)=>x.trim()).filter(Boolean)}:null;emit('save',{record:payload(),commercial,bom:props.centerKey==='solutions'?{items:(draft.bom?.items||[]).map((item:any)=>({productId:item.productId,quantity:item.quantity,unit:item.unit,purpose:item.purpose,requirementLevel:item.requirementLevel,recommendationReason:item.recommendationReason}))}:null})}finally{saving.value=false}}
function add(target:string,values:any={}){(draft[target]||=[]).push(row(values))}
function addNested(parent:any,target:string,values:any={}){(parent[target]||=[]).push(row(values))}
function pairEntries(value:Record<string,string>={}){return Object.entries(value).map(([key,item])=>({key,value:item}))}
const deploymentRows=computed({get:()=>pairEntries(draft.deploymentRequirements||{}),set:(rows:any[])=>draft.deploymentRequirements=Object.fromEntries(rows.filter(x=>x.key).map(x=>[x.key,x.value]))})
function updateDeployment(rows:any[]){draft.deploymentRequirements=Object.fromEntries(rows.filter(x=>x.key).map(x=>[x.key,x.value]))}
</script>

<template>
  <div class="inline-editor">
    <div class="edit-banner"><span>正在原位编辑{{ title }}，切换页签不会丢失未保存内容</span><div><el-button @click="emit('cancel')">取消</el-button><el-button type="primary" :icon="Select" :loading="saving" @click="save">保存全部修改</el-button></div></div>

    <section v-if="activeTab==='overview'" class="edit-section">
      <div class="section-head"><div><h2>基本信息</h2><p>字段保存后直接回到当前详情布局。</p></div></div>
      <el-form label-position="top" class="form-grid">
        <el-form-item label="名称"><el-input v-model="draft.name"/></el-form-item><el-form-item v-if="centerKey!=='scenes'" label="编码"><el-input v-model="draft.code"/></el-form-item>
        <el-form-item v-if="centerKey!=='scenes'" label="版本"><el-input v-model="draft.version"/></el-form-item><el-form-item label="分类"><el-input v-model="draft.category"/></el-form-item>
        <el-form-item label="状态"><el-input v-model="draft.status"/></el-form-item><el-form-item v-if="centerKey==='software'" label="厂商"><el-input v-model="draft.vendor"/></el-form-item>
        <el-form-item v-if="centerKey==='software'" label="软件类型"><el-select v-model="draft.softwareType"><el-option label="平台软件" value="PLATFORM"/><el-option label="客户端软件" value="CLIENT"/><el-option label="服务组件" value="SERVICE"/></el-select></el-form-item>
        <el-form-item v-if="centerKey==='model-capabilities'" label="模型类型"><el-input v-model="draft.modelType"/></el-form-item><el-form-item v-if="centerKey==='model-capabilities'" label="任务类型"><el-input v-model="draft.taskType"/></el-form-item><el-form-item v-if="centerKey==='model-capabilities'" label="功能类型"><el-input v-model="draft.functionType"/></el-form-item>
        <el-form-item v-if="centerKey==='solutions'" label="方案等级"><el-select v-model="draft.tier"><el-option label="标准型" value="STANDARD"/><el-option label="增强型" value="ENHANCED"/><el-option label="旗舰型" value="FLAGSHIP"/></el-select></el-form-item>
        <el-form-item label="简介" class="span-2"><el-input v-model="draft.summary" type="textarea" :rows="3"/></el-form-item><el-form-item v-if="centerKey==='software'" label="详细说明" class="span-2"><el-input v-model="draft.description" type="textarea" :rows="4"/></el-form-item>
      </el-form>
      <ImageUpload v-if="centerKey==='software'" v-model="draft.logo" label="软件 Logo"/><ImageUpload v-if="centerKey==='scenes'" v-model="draft.coverImage" label="场景封面"/><ImageUpload v-if="centerKey==='solutions'" v-model="draft.coverImage" label="方案封面"/>
    </section>

    <section v-else-if="centerKey==='software'" class="edit-section">
      <template v-if="activeTab==='commercial'"><el-form label-position="top" class="form-grid"><el-form-item label="物料代码"><el-input v-model="draft.commercial.materialCode"/></el-form-item><el-form-item label="单位"><el-input v-model="draft.commercial.unit"/></el-form-item><el-form-item label="商业状态"><el-select v-model="draft.commercial.commercialStatus"><el-option label="主推" value="FEATURED"/><el-option label="在售" value="ACTIVE"/><el-option label="库存" value="INVENTORY"/><el-option label="停售" value="DISCONTINUED"/></el-select></el-form-item><el-form-item label="默认质保（月）"><el-input-number v-model="draft.commercial.warrantyMonths" :min="0"/></el-form-item><el-form-item v-if="showPrice" label="代理单价"><el-input-number v-model="draft.commercial.agentPrice" :min="0"/></el-form-item><el-form-item v-if="showPrice" label="销售单价"><el-input-number v-model="draft.commercial.salePrice" :min="0"/></el-form-item><el-form-item label="延保规则" class="span-2"><el-input v-model="draft.commercial.extendedWarrantyRule"/></el-form-item><el-form-item label="适用场景" class="span-2"><el-select v-model="draft.commercial.applicableScenes" multiple allow-create filterable/></el-form-item><el-form-item label="销售备注" class="span-2"><el-input v-model="draft.commercial.salesNotes" type="textarea"/></el-form-item></el-form></template>
      <template v-else-if="activeTab==='functions'"><RepeaterTitle title="系统功能" @add="add('modules',{features:[]})"/><article v-for="(item,index) in draft.modules" :key="index" class="nested-card"><div class="row three"><el-input v-model="item.name" placeholder="模块名称"/><el-input v-model="item.description" placeholder="模块说明"/><el-button :icon="Delete" circle type="danger" plain @click="draft.modules.splice(index,1)"/></div><div v-for="(feature,fi) in item.features" :key="fi" class="row three child"><el-input v-model="feature.name" placeholder="功能名称"/><el-input v-model="feature.description" placeholder="功能说明"/><el-button :icon="Delete" circle plain @click="item.features.splice(fi,1)"/></div><el-button link :icon="Plus" @click="addNested(item,'features')">添加子功能</el-button></article></template>
      <template v-else-if="activeTab==='versions'"><RepeaterTitle title="版本信息" @add="add('versions',{version:'',releasedAt:null,summary:''})"/><div v-for="(item,index) in draft.versions" :key="index" class="row four"><el-input v-model="item.version" placeholder="版本"/><el-date-picker v-model="item.releasedAt" type="date" value-format="YYYY-MM-DD"/><el-input v-model="item.summary" placeholder="更新说明"/><el-button :icon="Delete" circle type="danger" plain @click="draft.versions.splice(index,1)"/></div></template>
      <template v-else-if="activeTab==='deployment'"><div class="form-grid"><el-form-item label="部署方式"><el-select v-model="draft.deploymentMode"><el-option label="私有化部署" value="PRIVATE"/><el-option label="云端部署" value="CLOUD"/><el-option label="混合部署" value="HYBRID"/></el-select></el-form-item><StringList v-model="draft.supportedOs" title="操作系统"/><StringList v-model="draft.databases" title="数据库"/><StringList v-model="draft.protocols" title="支持协议"/></div></template>
      <StringList v-else-if="activeTab==='boundaries'" v-model="draft.boundaries" title="能力边界"/>
      <template v-else-if="activeTab==='screenshots'"><RepeaterTitle title="软件截图" @add="add('screenshots',{image:'',title:''})"/><article v-for="(item,index) in draft.screenshots" :key="index" class="media-row"><ImageUpload v-model="item.image" :label="item.title||'软件截图'"/><el-input v-model="item.title" placeholder="图片说明"/><el-button :icon="Delete" circle type="danger" plain @click="draft.screenshots.splice(index,1)"/></article></template>
    </section>

    <section v-else-if="centerKey==='algorithms'" class="edit-section">
      <el-form v-if="activeTab==='commercial'" label-position="top" class="form-grid"><el-form-item label="物料代码"><el-input v-model="draft.commercial.materialCode"/></el-form-item><el-form-item label="授权单位"><el-input v-model="draft.commercial.licenseUnit"/></el-form-item><el-form-item label="基础路数"><el-input-number v-model="draft.commercial.includedQuantity" :min="0"/></el-form-item><el-form-item label="交付方式"><el-input v-model="draft.commercial.deliveryMethod"/></el-form-item><el-form-item v-if="showPrice" label="代理单价"><el-input-number v-model="draft.commercial.agentPrice" :min="0"/></el-form-item><el-form-item v-if="showPrice" label="销售单价"><el-input-number v-model="draft.commercial.salePrice" :min="0"/></el-form-item><el-form-item v-if="showPrice" label="超额单价"><el-input-number v-model="draft.commercial.overageUnitPrice" :min="0"/></el-form-item><el-form-item label="适用场景" class="span-2"><el-select v-model="draft.commercial.applicableScenes" multiple allow-create filterable/></el-form-item><el-form-item label="销售备注" class="span-2"><el-input v-model="draft.commercial.salesNotes" type="textarea"/></el-form-item></el-form>
      <el-form v-else-if="['principle','input','output'].includes(activeTab)" label-position="top"><el-form-item :label="activeTab==='principle'?'算法原理':activeTab==='input'?'输入数据':'输出结果'"><el-input v-model="draft[activeTab==='principle'?'principle':activeTab==='input'?'inputSummary':'outputSummary']" type="textarea" :rows="8"/></el-form-item></el-form>
      <MetricRows v-else-if="activeTab==='parameters'" v-model="draft.parameters" title="核心参数" :evidence="false"/>
      <MetricRows v-else-if="activeTab==='metrics'" v-model="draft.metrics" title="性能指标" :evidence="true"/>
      <StringList v-else-if="activeTab==='boundaries'" v-model="draft.boundaries" title="能力边界"/>
    </section>

    <section v-else-if="centerKey==='model-capabilities'" class="edit-section">
      <MetricRows v-if="activeTab==='metrics'" v-model="draft.metrics" title="性能指标与测试依据" :evidence="true" :model-evidence="true"/>
      <DefinitionRows v-else-if="activeTab==='input'" v-model="draft.inputDefinitions" title="输入要求" :input="true"/>
      <DefinitionRows v-else-if="activeTab==='output'" v-model="draft.outputDefinitions" title="输出定义"/>
      <template v-else-if="activeTab==='deployment'"><RepeaterTitle title="部署规格" @add="updateDeployment([...deploymentRows,{key:'',value:''}])"/><div v-for="(item,index) in deploymentRows" :key="index" class="row three"><el-input v-model="item.key" placeholder="规格项" @input="updateDeployment(deploymentRows)"/><el-input v-model="item.value" placeholder="要求" @input="updateDeployment(deploymentRows)"/><el-button :icon="Delete" circle type="danger" plain @click="updateDeployment(deploymentRows.filter((_,i)=>i!==index))"/></div><StringList v-model="draft.useConditions" title="使用条件"/></template>
      <StringList v-else-if="activeTab==='boundaries'" v-model="draft.boundaries" title="能力边界"/>
    </section>

    <section v-else-if="centerKey==='scenes'" class="edit-section">
      <ItemRows v-if="activeTab==='pains'" v-model="draft.painPoints" title="业务痛点"/><ItemRows v-else-if="activeTab==='goals'" v-model="draft.goals" title="建设目标"/><StringList v-else-if="activeTab==='conditions'" v-model="draft.conditions" title="关键条件"/>
      <template v-else-if="activeTab==='matrix'"><el-form label-position="top"><el-form-item label="核心能力说明"><el-input v-model="draft.coreCapabilitySummary" type="textarea" :rows="8"/></el-form-item></el-form></template>
      <template v-else-if="activeTab==='process'"><RepeaterTitle title="业务流程" @add="add('process',{nodeTitle:'',nodeDescription:''})"/><div v-for="(item,index) in draft.process" :key="index" class="row three"><el-input v-model="item.nodeTitle" placeholder="节点名称"/><el-input v-model="item.nodeDescription" placeholder="节点说明"/><el-button :icon="Delete" circle type="danger" plain @click="draft.process.splice(index,1)"/></div></template>
    </section>

    <section v-else-if="centerKey==='solutions'" class="edit-section">
      <el-form v-if="activeTab==='conditions'" label-position="top" class="form-grid"><el-form-item label="关联场景"><el-input-number v-model="draft.sceneId" :min="1"/></el-form-item><el-form-item label="适用范围"><el-input v-model="draft.coverageScope"/></el-form-item><el-form-item label="目标说明" class="span-2"><el-input v-model="draft.targetDescription" type="textarea" :rows="5"/></el-form-item><el-form-item label="实施说明" class="span-2"><el-input v-model="draft.implementationNotes" type="textarea" :rows="5"/></el-form-item></el-form>
      <template v-else-if="activeTab==='architecture' || activeTab==='composition'"><RepeaterTitle title="系统架构" @add="add('architecture',{layer:'感知层',relationType:'',relationId:null})"/><div v-for="(item,index) in draft.architecture" :key="index" class="row architecture"><el-input v-model="item.layer" placeholder="层级"/><el-input v-model="item.name" placeholder="组成名称"/><el-input v-model="item.description" placeholder="说明"/><el-button :icon="Delete" circle type="danger" plain @click="draft.architecture.splice(index,1)"/></div></template>
      <template v-else-if="activeTab==='coverage'"><RepeaterTitle title="能力覆盖" @add="add('capabilityCoverage',{capabilityName:'',status:'COVERED',implementation:'',notes:''})"/><div v-for="(item,index) in draft.capabilityCoverage" :key="index" class="row coverage"><el-input v-model="item.capabilityName" placeholder="能力名称"/><el-select v-model="item.status"><el-option label="已覆盖" value="COVERED"/><el-option label="可选" value="OPTIONAL"/><el-option label="未覆盖" value="NOT_COVERED"/></el-select><el-input v-model="item.implementation" placeholder="实现方式"/><el-input v-model="item.notes" placeholder="说明"/><el-button :icon="Delete" circle type="danger" plain @click="draft.capabilityCoverage.splice(index,1)"/></div></template>
      <template v-else-if="activeTab==='bom'"><RepeaterTitle title="标准BOM" @add="(draft.bom.items||=[]).push({productId:products[0]?.id,quantity:1,unit:'台',purpose:'',requirementLevel:'REQUIRED',recommendationReason:''})"/><div v-for="(item,index) in draft.bom.items" :key="index" class="row bom"><el-select v-model="item.productId" filterable><el-option v-for="product in products" :key="product.id" :label="product.name+' · '+product.modelCode" :value="product.id"/></el-select><el-input-number v-model="item.quantity" :min="1"/><el-input v-model="item.unit" placeholder="单位"/><el-input v-model="item.purpose" placeholder="用途"/><el-select v-model="item.requirementLevel"><el-option label="必需" value="REQUIRED"/><el-option label="推荐" value="RECOMMENDED"/><el-option label="可选" value="OPTIONAL"/></el-select><el-input v-model="item.recommendationReason" placeholder="推荐理由"/><el-button :icon="Delete" circle type="danger" plain @click="draft.bom.items.splice(index,1)"/></div></template>
    </section>
  </div>
</template>

<script lang="ts">
import { defineComponent, h } from 'vue'
import { ElButton, ElCheckbox, ElInput, ElSelect, ElOption } from 'element-plus'
export const RepeaterTitle=defineComponent({props:{title:String},emits:['add'],setup(p,{emit}){return()=>h('div',{class:'repeater-title'},[h('div',[h('h2',p.title),h('p','可在当前板块新增、修改和删除。')]),h(ElButton,{icon:Plus,onClick:()=>emit('add')},()=> '新增')])}})
export const StringList=defineComponent({props:{modelValue:{type:Array,default:()=>[]},title:String},emits:['update:modelValue'],setup(p,{emit}){const update=(list:any[])=>emit('update:modelValue',list);return()=>h('div',[h(RepeaterTitle,{title:p.title,onAdd:()=>update([...(p.modelValue as any[]),''])}),...(p.modelValue as any[]).map((item,index)=>h('div',{class:'row two'},[h(ElInput,{modelValue:item,'onUpdate:modelValue':(v:any)=>{const list=[...(p.modelValue as any[])];list[index]=v;update(list)},placeholder:'请输入内容'}),h(ElButton,{icon:Delete,circle:true,type:'danger',plain:true,onClick:()=>update((p.modelValue as any[]).filter((_,i)=>i!==index))})]))])}})
export const ItemRows=defineComponent({props:{modelValue:{type:Array,default:()=>[]},title:String},emits:['update:modelValue'],setup(p,{emit}){const update=()=>emit('update:modelValue',[...(p.modelValue as any[])]);return()=>h('div',[h(RepeaterTitle,{title:p.title,onAdd:()=>{(p.modelValue as any[]).push({title:'',description:'',icon:'',sortOrder:(p.modelValue as any[]).length});update()}}),...(p.modelValue as any[]).map((item,index)=>h('div',{class:'row three'},[h(ElInput,{modelValue:item.title,'onUpdate:modelValue':(v:any)=>{item.title=v;update()},placeholder:'标题'}),h(ElInput,{modelValue:item.description,'onUpdate:modelValue':(v:any)=>{item.description=v;update()},placeholder:'说明'}),h(ElButton,{icon:Delete,circle:true,type:'danger',plain:true,onClick:()=>{(p.modelValue as any[]).splice(index,1);update()}})]))])}})
export const MetricRows=defineComponent({props:{modelValue:{type:Array,default:()=>[]},title:String,evidence:Boolean,modelEvidence:Boolean},emits:['update:modelValue'],setup(p,{emit}){const update=()=>emit('update:modelValue',[...(p.modelValue as any[])]);return()=>h('div',[h(RepeaterTitle,{title:p.title,onAdd:()=>{(p.modelValue as any[]).push({name:'',value:'',unit:'',group:'性能指标',condition:'',source:'',dataset:'',sampleCount:'',inputResolution:'',hardware:'',runtime:'',highlight:false,sortOrder:(p.modelValue as any[]).length});update()}}),...(p.modelValue as any[]).map((item,index)=>h('article',{class:'metric-editor'},[h('div',{class:'row metric'},[h(ElInput,{modelValue:item.name,'onUpdate:modelValue':(v:any)=>{item.name=v;update()},placeholder:'指标名称'}),h(ElInput,{modelValue:item.value,'onUpdate:modelValue':(v:any)=>{item.value=v;update()},placeholder:'数值'}),h(ElInput,{modelValue:item.unit,'onUpdate:modelValue':(v:any)=>{item.unit=v;update()},placeholder:'单位'}),h(ElInput,{modelValue:item.group,'onUpdate:modelValue':(v:any)=>{item.group=v;update()},placeholder:'分组'}),h(ElCheckbox,{modelValue:item.highlight,'onUpdate:modelValue':(v:any)=>{item.highlight=v;update()}},()=> '重点'),h(ElButton,{icon:Delete,circle:true,type:'danger',plain:true,onClick:()=>{(p.modelValue as any[]).splice(index,1);update()}})]),p.evidence?h('div',{class:'row evidence'},[h(ElInput,{modelValue:item.condition,'onUpdate:modelValue':(v:any)=>{item.condition=v;update()},placeholder:'测试条件'}),h(ElInput,{modelValue:item.source,'onUpdate:modelValue':(v:any)=>{item.source=v;update()},placeholder:'来源/报告'}),...(p.modelEvidence?[['dataset','数据集'],['sampleCount','样本数'],['inputResolution','输入分辨率'],['hardware','测试硬件'],['runtime','运行环境']].map(([key,label])=>h(ElInput,{modelValue:item[key],'onUpdate:modelValue':(v:any)=>{item[key]=v;update()},placeholder:label})):[]) ]):null]))])}})
export const DefinitionRows=defineComponent({props:{modelValue:{type:Array,default:()=>[]},title:String,input:Boolean},emits:['update:modelValue'],setup(p,{emit}){const update=()=>emit('update:modelValue',[...(p.modelValue as any[])]);return()=>h('div',[h(RepeaterTitle,{title:p.title,onAdd:()=>{(p.modelValue as any[]).push({name:'',dataType:'JSON',required:false,description:'',example:'',sortOrder:(p.modelValue as any[]).length});update()}}),...(p.modelValue as any[]).map((item,index)=>h('div',{class:'row definition'},[h(ElInput,{modelValue:item.name,'onUpdate:modelValue':(v:any)=>{item.name=v;update()},placeholder:'字段名称'}),h(ElInput,{modelValue:item.dataType,'onUpdate:modelValue':(v:any)=>{item.dataType=v;update()},placeholder:'数据类型'}),h(ElInput,{modelValue:item.description,'onUpdate:modelValue':(v:any)=>{item.description=v;update()},placeholder:'定义说明'}),h(ElInput,{modelValue:item.example,'onUpdate:modelValue':(v:any)=>{item.example=v;update()},placeholder:'示例'}),p.input?h(ElCheckbox,{modelValue:item.required,'onUpdate:modelValue':(v:any)=>{item.required=v;update()}},()=> '必填'):null,h(ElButton,{icon:Delete,circle:true,type:'danger',plain:true,onClick:()=>{(p.modelValue as any[]).splice(index,1);update()}})]))])}})
</script>

<style scoped>
.inline-editor{display:grid;gap:14px}.edit-banner,.edit-section{padding:16px 18px;border:1px solid #dfe7f1;border-radius:8px;background:#fff}.edit-banner{display:flex;align-items:center;justify-content:space-between;background:#eaf3ff;border-color:#bdd7ff;color:#1557aa;font-weight:600}.edit-banner>div{display:flex;gap:8px}.section-head,.repeater-title{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:14px}.section-head h2,.repeater-title h2{margin:0;font-size:17px}.section-head p,.repeater-title p{margin:5px 0 0;color:#77869a;font-size:12px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 16px}.span-2{grid-column:1/-1}.form-grid :deep(.el-select){width:100%}.nested-card,.metric-editor{display:grid;gap:8px;margin-bottom:10px;padding:12px;border:1px solid #e4eaf2;border-radius:6px}.row{display:grid;gap:8px;align-items:center;margin-bottom:8px}.row.two{grid-template-columns:1fr 34px}.row.three{grid-template-columns:180px 1fr 34px}.row.four{grid-template-columns:150px 180px 1fr 34px}.row.metric{grid-template-columns:1.4fr 1fr 80px 120px 72px 34px}.row.evidence{grid-template-columns:repeat(auto-fit,minmax(130px,1fr))}.row.definition{grid-template-columns:140px 110px 1fr 1fr auto 34px}.row.architecture{grid-template-columns:130px 180px 1fr 34px}.row.coverage{grid-template-columns:170px 120px 1fr 1fr 34px}.row.bom{grid-template-columns:220px 100px 75px 1fr 115px 1fr 34px}.child{padding-left:18px}.media-row{display:grid;grid-template-columns:minmax(300px,1fr) 1fr 34px;gap:9px;align-items:center;margin-bottom:10px}@media(max-width:900px){.row,.row.three,.row.four,.row.metric,.row.definition,.row.architecture,.row.coverage,.row.bom,.media-row{grid-template-columns:1fr 34px}.row>*:not(:last-child),.media-row>*:not(:last-child){grid-column:1}.row>*:last-child,.media-row>*:last-child{grid-column:2;grid-row:1}.form-grid{grid-template-columns:1fr}.span-2{grid-column:auto}}@media(max-width:600px){.edit-banner{align-items:stretch;flex-direction:column}.edit-banner>div{justify-content:flex-end}}
</style>
