<script setup lang="ts">
import { computed, ref } from 'vue'
import { ArrowDown, ArrowUp, Grid, List, Plus, Refresh, Search } from '@element-plus/icons-vue'
import ProductVisual from './ProductVisual.vue'
const props=withDefaults(defineProps<{rows:any[];loading?:boolean;error?:string;canManage?:boolean;showPrice?:boolean}>(),{loading:false,error:'',canManage:false,showPrice:false})
const emit=defineEmits<{create:[];open:[row:any];edit:[row:any];delete:[row:any];move:[row:any,direction:number];retry:[]}>()
const keyword=ref(''),type=ref('ALL'),status=ref('ALL'),view=ref<'card'|'list'>('card')
const typeLabels:Record<string,string>={HARDWARE:'硬件产品',SOFTWARE_PRODUCT:'软件产品',SYSTEM_PRODUCT:'系统产品',ACCESSORY:'配套设备'}
const visible=computed(()=>props.rows.filter(row=>(!keyword.value||[row.name,row.modelCode,row.category,row.summary].join(' ').toLowerCase().includes(keyword.value.toLowerCase()))&&(type.value==='ALL'||row.productType===type.value)&&(status.value==='ALL'||row.status===status.value)))
const money=(row:any)=>row.defaultOffer?`${row.defaultOffer.currency==='CNY'?'¥':row.defaultOffer.currency} ${Number(row.defaultOffer.amount).toLocaleString()} · ${row.defaultOffer.warrantyMonths?row.defaultOffer.warrantyMonths/12+'年质保':''}`:'价格待确认'
</script>
<template>
<section class="product-page" v-loading="loading">
 <header class="page-title"><div><span class="eyebrow">PRODUCT KNOWLEDGE</span><h1>产品中心</h1><p>统一查阅产品型号、核心参数、适配能力与商业信息。</p></div><el-button v-if="canManage" type="primary" :icon="Plus" @click="emit('create')">新增产品</el-button></header>
 <div class="product-metrics"><div><strong>{{rows.length}}</strong><span>全部产品</span></div><div><strong>{{rows.filter(x=>x.status==='ON_SALE').length}}</strong><span>在售产品</span></div><div><strong>{{new Set(rows.map(x=>x.category)).size}}</strong><span>产品分类</span></div></div>
 <div class="toolbar"><el-input v-model="keyword" :prefix-icon="Search" placeholder="搜索产品名称、主型号或分类" clearable/><el-select v-model="type"><el-option label="全部类型" value="ALL"/><el-option v-for="(label,key) in typeLabels" :key="key" :label="label" :value="key"/></el-select><el-select v-model="status"><el-option label="全部状态" value="ALL"/><el-option label="在售" value="ON_SALE"/><el-option label="停售" value="OFF_SALE"/></el-select><div class="view"><el-tooltip content="卡片视图"><el-button :type="view==='card'?'primary':'default'" :icon="Grid" @click="view='card'"/></el-tooltip><el-tooltip content="列表视图"><el-button :type="view==='list'?'primary':'default'" :icon="List" @click="view='list'"/></el-tooltip></div></div>
 <el-alert v-if="error" type="error" :title="error" :closable="false" show-icon><el-button :icon="Refresh" @click="emit('retry')">重新加载</el-button></el-alert>
 <div v-else-if="!loading&&visible.length&&view==='card'" class="grid"><article v-for="row in visible" :key="row.id" class="product-card" @click="emit('open',row)"><div class="image"><ProductVisual :src="row.mainImage" :alt="row.name"/><span class="sale" :class="{off:row.status!=='ON_SALE'}">{{row.status==='ON_SALE'?'在售':'停售'}}</span></div><div class="body"><div class="identity"><span>{{typeLabels[row.productType]||'产品'}}</span><span>{{row.category}}</span></div><h2>{{row.name}}</h2><p class="model">{{row.modelCode}} · {{row.currentVersion||'v1.0'}}</p><p class="summary">{{row.summary||'产品简介待完善'}}</p><div class="params"><span v-for="item in (row.parameters||[]).filter((x:any)=>x.highlight).slice(0,4)" :key="item.id||item.name"><b>{{item.value}}{{item.unit}}</b>{{item.name}}</span><span v-if="!(row.parameters||[]).some((x:any)=>x.highlight)" class="muted">核心参数待完善</span></div><footer><span>更新于 {{new Date(row.updatedAt).toLocaleDateString()}}</span><strong v-if="showPrice">{{money(row)}}</strong></footer><div v-if="canManage" class="actions"><el-button link :icon="ArrowUp" aria-label="上移" @click.stop="emit('move',row,-1)"/><el-button link :icon="ArrowDown" aria-label="下移" @click.stop="emit('move',row,1)"/><el-button link @click.stop="emit('edit',row)">编辑</el-button><el-button link type="danger" @click.stop="emit('delete',row)">删除</el-button></div></div></article></div>
 <el-table v-else-if="!loading&&visible.length" :data="visible" row-key="id" @row-click="emit('open',$event)"><el-table-column label="产品" min-width="250"><template #default="s"><div class="table-product"><div><ProductVisual :src="s.row.mainImage" :alt="s.row.name"/></div><span><b>{{s.row.name}}</b><small>{{s.row.modelCode}}</small></span></div></template></el-table-column><el-table-column label="版本" prop="currentVersion" width="100"/><el-table-column label="类型" min-width="150"><template #default="s">{{typeLabels[s.row.productType]}}</template></el-table-column><el-table-column label="分类" prop="category" min-width="130"/><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="s.row.status==='ON_SALE'?'success':'info'" effect="plain">{{s.row.status==='ON_SALE'?'在售':'停售'}}</el-tag></template></el-table-column><el-table-column v-if="showPrice" label="参考价格" min-width="130"><template #default="s">{{money(s.row)}}</template></el-table-column><el-table-column label="更新时间" width="130"><template #default="s">{{new Date(s.row.updatedAt).toLocaleDateString()}}</template></el-table-column></el-table>
 <el-empty v-else-if="!loading" description="暂无匹配的产品"/>
</section>
</template>
<style scoped>
.product-page{display:grid;gap:18px}.page-title{display:flex;justify-content:space-between;gap:20px}.eyebrow{color:#146ef5;font-size:11px;font-weight:750}.page-title h1{margin:5px 0 6px;font-size:27px}.page-title p{margin:0;color:#66758d}.product-metrics{display:flex;gap:0;background:#fff;border:1px solid #e3eaf2}.product-metrics div{min-width:180px;padding:14px 22px;border-right:1px solid #edf1f5}.product-metrics strong{display:block;font-size:24px;color:#152640}.product-metrics span{font-size:12px;color:#7b899c}.toolbar{display:grid;grid-template-columns:minmax(280px,1fr) 170px 130px auto;gap:10px}.view{display:flex}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.product-card{overflow:hidden;background:#fff;border:1px solid #e1e8f1;border-radius:8px;cursor:pointer;transition:.18s}.product-card:hover{border-color:#8dbbfa;box-shadow:0 10px 28px rgba(31,75,132,.11);transform:translateY(-2px)}.image{position:relative;height:154px}.sale{position:absolute;top:12px;right:12px;padding:4px 9px;border-radius:4px;background:#eaf9f1;color:#0b8050;font-size:12px}.sale.off{background:#f2f4f7;color:#667085}.body{position:relative;padding:16px}.identity{display:flex;gap:7px;color:#55708f;font-size:11px}.identity span{padding:3px 6px;background:#f1f6fb;border-radius:3px}.body h2{margin:11px 0 4px;font-size:18px}.model{margin:0;color:#146ef5;font-size:12px;font-weight:650}.summary{height:42px;margin:10px 0;color:#65748a;line-height:1.5;overflow:hidden}.params{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;min-height:63px}.params span{display:grid;padding:6px 8px;background:#f7f9fc;color:#768399;font-size:10px}.params b{color:#263a56;font-size:13px}.params .muted{grid-column:1/-1;place-items:center}.body footer{display:flex;justify-content:space-between;margin-top:13px;padding-top:12px;border-top:1px solid #edf1f5;color:#8894a5;font-size:11px}.body footer strong{color:#cf7a00;font-size:13px}.actions{position:absolute;right:12px;top:10px;display:none;padding:2px;background:#fff}.product-card:hover .actions{display:flex}.table-product{display:flex;align-items:center;gap:10px}.table-product>div{width:48px;height:40px}.table-product span{display:grid}.table-product small{color:#7a8799}@media(max-width:1350px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:760px){.page-title{flex-direction:column}.toolbar{grid-template-columns:1fr 1fr}.toolbar>:first-child{grid-column:1/-1}.grid{grid-template-columns:1fr}.product-metrics div{min-width:0;flex:1;padding:12px}.product-metrics{overflow:auto}}
.image{min-height:154px;overflow:hidden}.image :deep(.visual),.image :deep(.visual img){min-height:0}
</style>
