<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Delete, Edit, Plus, Refresh, UserFilled } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
const props=defineProps<{token:string}>()
const users=ref<any[]>([]),roles=ref<any[]>([]),permissions=ref<any[]>([]),directory=ref<any>({}),loading=ref(false),userDialog=ref(false),roleDialog=ref(false),editingUser=ref<any>(null),editingRole=ref<any>(null)
const userForm=reactive<any>({username:'',display_name:'',password:'',role_code:'',email:'',department:'',enabled:true})
const roleForm=reactive<any>({code:'',name:'',permissions:[]})
async function api(url:string,options:any={}){const response=await fetch(url,{...options,headers:{'Content-Type':'application/json',Authorization:'Bearer '+props.token,...(options.headers||{})}});const data=response.status===204?null:await response.json();if(!response.ok)throw Error(data?.detail||'请求失败');return data}
async function load(){loading.value=true;try{[users.value,roles.value,permissions.value,directory.value]=await Promise.all([api('/api/admin/users'),api('/api/admin/roles'),api('/api/admin/permissions'),api('/api/admin/directory/status')])}finally{loading.value=false}}
function addUser(){editingUser.value=null;Object.assign(userForm,{username:'',display_name:'',password:'',role_code:roles.value[0]?.code||'',email:'',department:'',enabled:true});userDialog.value=true}
function editUser(row:any){editingUser.value=row;Object.assign(userForm,{username:row.username,display_name:row.displayName,password:'',role_code:row.roleCode,email:row.email,department:row.department,enabled:row.enabled});userDialog.value=true}
async function saveUser(){const body={...userForm};if(editingUser.value){delete body.username;if(!body.password)delete body.password}await api(editingUser.value?'/api/admin/users/'+editingUser.value.id:'/api/admin/users',{method:editingUser.value?'PATCH':'POST',body:JSON.stringify(body)});userDialog.value=false;ElMessage.success('用户已保存');await load()}
async function removeUser(row:any){await ElMessageBox.confirm('确认删除用户 '+row.username+'？','删除用户',{type:'warning'});await api('/api/admin/users/'+row.id,{method:'DELETE'});ElMessage.success('用户已删除');await load()}
function addRole(){editingRole.value=null;Object.assign(roleForm,{code:'',name:'',permissions:[]});roleDialog.value=true}
function editRole(row:any){editingRole.value=row;Object.assign(roleForm,{code:row.code,name:row.name,permissions:[...row.permissions]});roleDialog.value=true}
async function saveRole(){const body={name:roleForm.name,permissions:roleForm.permissions,...(!editingRole.value?{code:roleForm.code}:{})};await api(editingRole.value?'/api/admin/roles/'+editingRole.value.code:'/api/admin/roles',{method:editingRole.value?'PATCH':'POST',body:JSON.stringify(body)});roleDialog.value=false;ElMessage.success('角色与权限已保存');await load()}
async function removeRole(row:any){await ElMessageBox.confirm('确认删除角色 '+row.name+'？','删除角色',{type:'warning'});await api('/api/admin/roles/'+row.code,{method:'DELETE'});ElMessage.success('角色已删除');await load()}
async function syncAd(){try{const result=await api('/api/admin/directory/sync',{method:'POST'});ElMessage.success(`同步完成：新增 ${result.created}，更新 ${result.updated}，停用 ${result.disabled}`);await load()}catch(error:any){ElMessage.error(error.message)}}
onMounted(load)
</script>
<template><section class="system-page" v-loading="loading"><div class="page-head"><div><h1>系统管理</h1><p>统一管理本地用户、AD 域用户、角色与敏感权限。</p></div></div><el-tabs><el-tab-pane label="用户管理"><div class="toolbar"><el-button type="primary" :icon="Plus" @click="addUser">新增用户</el-button></div><el-table :data="users" border><el-table-column prop="username" label="账号"/><el-table-column prop="displayName" label="姓名"/><el-table-column prop="department" label="部门"/><el-table-column prop="email" label="邮箱"/><el-table-column prop="roleName" label="角色"/><el-table-column label="来源"><template #default="scope"><el-tag :type="scope.row.authSource==='AD'?'success':'info'">{{scope.row.authSource==='AD'?'AD 域':'本地'}}</el-tag></template></el-table-column><el-table-column label="状态"><template #default="scope">{{scope.row.enabled?'启用':'停用'}}</template></el-table-column><el-table-column width="110"><template #default="scope"><el-button link :icon="Edit" @click="editUser(scope.row)"/><el-button link type="danger" :icon="Delete" @click="removeUser(scope.row)"/></template></el-table-column></el-table></el-tab-pane><el-tab-pane label="角色与权限"><div class="toolbar"><el-button type="primary" :icon="Plus" @click="addRole">新增角色</el-button></div><el-table :data="roles" border><el-table-column prop="name" label="角色名称"/><el-table-column prop="code" label="角色编码"/><el-table-column label="权限"><template #default="scope"><el-tag v-for="code in scope.row.permissions" :key="code" effect="plain">{{permissions.find(item=>item.code===code)?.name||code}}</el-tag></template></el-table-column><el-table-column width="110"><template #default="scope"><el-button link :icon="Edit" @click="editRole(scope.row)"/><el-button link type="danger" :icon="Delete" @click="removeRole(scope.row)"/></template></el-table-column></el-table></el-tab-pane><el-tab-pane label="AD 域同步"><article class="directory-card"><div><el-icon><UserFilled/></el-icon><span><strong>Active Directory</strong><small>{{directory.configured?'连接参数已配置':'等待服务器配置连接参数'}}</small></span></div><dl><div><dt>服务器</dt><dd>{{directory.server||'未配置'}}</dd></div><div><dt>Base DN</dt><dd>{{directory.baseDn||'未配置'}}</dd></div><div><dt>默认角色</dt><dd>{{directory.defaultRole||'-'}}</dd></div><div><dt>上次同步</dt><dd>{{directory.lastRun?.finishedAt||'尚未同步'}}</dd></div></dl><el-alert v-if="directory.lastRun?.status==='FAILED'" :title="directory.lastRun.error" type="error" show-icon/><el-button type="primary" :icon="Refresh" :disabled="!directory.configured" @click="syncAd">立即同步域用户</el-button></article></el-tab-pane></el-tabs>
<el-dialog v-model="userDialog" :title="editingUser?'编辑用户':'新增用户'" width="620px"><el-form label-position="top" class="grid"><el-form-item label="账号"><el-input v-model="userForm.username" :disabled="!!editingUser"/></el-form-item><el-form-item label="姓名"><el-input v-model="userForm.display_name"/></el-form-item><el-form-item :label="editingUser?'重置密码（留空不修改）':'初始密码'"><el-input v-model="userForm.password" type="password" show-password :disabled="editingUser?.authSource==='AD'"/></el-form-item><el-form-item label="角色"><el-select v-model="userForm.role_code"><el-option v-for="item in roles" :key="item.code" :label="item.name" :value="item.code"/></el-select></el-form-item><el-form-item label="部门"><el-input v-model="userForm.department"/></el-form-item><el-form-item label="邮箱"><el-input v-model="userForm.email"/></el-form-item><el-form-item label="启用"><el-switch v-model="userForm.enabled"/></el-form-item></el-form><template #footer><el-button @click="userDialog=false">取消</el-button><el-button type="primary" @click="saveUser">保存</el-button></template></el-dialog>
<el-dialog v-model="roleDialog" :title="editingRole?'编辑角色':'新增角色'" width="700px"><el-form label-position="top"><el-form-item label="角色编码"><el-input v-model="roleForm.code" :disabled="!!editingRole"/></el-form-item><el-form-item label="角色名称"><el-input v-model="roleForm.name"/></el-form-item><el-form-item label="权限"><el-checkbox-group v-model="roleForm.permissions" class="permission-grid"><el-checkbox v-for="item in permissions" :key="item.code" :value="item.code"><span><b>{{item.name}}</b><small>{{item.code}}</small></span></el-checkbox></el-checkbox-group></el-form-item></el-form><template #footer><el-button @click="roleDialog=false">取消</el-button><el-button type="primary" @click="saveRole">保存</el-button></template></el-dialog></section></template>
<style scoped>.system-page{display:grid;gap:14px}.page-head{display:flex;justify-content:space-between}.page-head h1{margin:0;font-size:26px}.page-head p{margin:6px 0;color:#69788c}.system-page :deep(.el-tabs){padding:16px 18px;background:#fff;border:1px solid #e2e9f2;border-radius:8px}.toolbar{display:flex;justify-content:flex-end;margin-bottom:12px}.system-page :deep(.el-tag){margin:2px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:0 14px}.grid :deep(.el-select){width:100%}.permission-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;width:100%}.permission-grid :deep(.el-checkbox){height:auto;margin:0;padding:10px;border:1px solid #e2e9f2}.permission-grid span{display:grid}.permission-grid small{color:#8290a2}.directory-card{max-width:760px;display:grid;gap:16px;padding:18px;border:1px solid #dfe7f0;border-radius:7px}.directory-card>div{display:flex;align-items:center;gap:12px}.directory-card span{display:grid}.directory-card small{color:#758398}.directory-card dl{margin:0}.directory-card dl div{display:flex;justify-content:space-between;padding:10px;border-bottom:1px solid #edf1f5}.directory-card dd{margin:0}@media(max-width:720px){.grid,.permission-grid{grid-template-columns:1fr}}</style>
