from datetime import datetime, timezone
from sqlalchemy import String, Text, Boolean, DateTime, ForeignKey, Integer, Numeric, UniqueConstraint, Index
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .database import Base

def now(): return datetime.now(timezone.utc)
class Timestamped:
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=now)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=now, onupdate=now)
class Role(Base, Timestamped):
    __tablename__='roles'; id:Mapped[int]=mapped_column(primary_key=True); code:Mapped[str]=mapped_column(String(64),unique=True); name:Mapped[str]=mapped_column(String(80)); permissions:Mapped[str]=mapped_column(Text,default=''); permission_links=relationship('RolePermission',cascade='all, delete-orphan',lazy='selectin')
class Permission(Base, Timestamped):
    __tablename__='permissions'; id:Mapped[int]=mapped_column(primary_key=True); code:Mapped[str]=mapped_column(String(80),unique=True); name:Mapped[str]=mapped_column(String(120)); description:Mapped[str]=mapped_column(Text,default='')
class RolePermission(Base):
    __tablename__='role_permissions'; role_id:Mapped[int]=mapped_column(ForeignKey('roles.id',ondelete='CASCADE'),primary_key=True); permission_id:Mapped[int]=mapped_column(ForeignKey('permissions.id',ondelete='CASCADE'),primary_key=True); permission=relationship(Permission,lazy='joined')
class User(Base, Timestamped):
    __tablename__='users'; id:Mapped[int]=mapped_column(primary_key=True); username:Mapped[str]=mapped_column(String(64),unique=True); display_name:Mapped[str]=mapped_column(String(80)); password_hash:Mapped[str]=mapped_column(String(255)); role_id:Mapped[int]=mapped_column(ForeignKey('roles.id')); enabled:Mapped[bool]=mapped_column(Boolean,default=True); email:Mapped[str]=mapped_column(String(160),default=''); department:Mapped[str]=mapped_column(String(160),default=''); auth_source:Mapped[str]=mapped_column(String(24),default='LOCAL'); external_id:Mapped[str|None]=mapped_column(String(255),nullable=True,unique=True); last_directory_sync_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); role=relationship(Role)
class ProductCategory(Base, Timestamped):
    __tablename__='product_categories'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(80),unique=True); description:Mapped[str]=mapped_column(Text,default='')
class Product(Base, Timestamped):
    __tablename__='products'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(160),unique=True); product_code:Mapped[str]=mapped_column(String(80),unique=True); product_series:Mapped[str]=mapped_column(String(100),default=''); model_code:Mapped[str]=mapped_column(String(80),unique=True); current_version:Mapped[str]=mapped_column(String(32),default='v1.0'); product_type:Mapped[str]=mapped_column(String(48),default='HARDWARE'); category_id:Mapped[int]=mapped_column(ForeignKey('product_categories.id')); summary:Mapped[str]=mapped_column(Text,default=''); description:Mapped[str]=mapped_column(Text,default=''); status:Mapped[str]=mapped_column(String(32),default='ON_SALE'); main_image:Mapped[str]=mapped_column(String(500),default=''); tags_json:Mapped[str]=mapped_column(Text,default='[]'); boundaries_json:Mapped[str]=mapped_column(Text,default='[]'); dynamic_fields_json:Mapped[str]=mapped_column(Text,default='{}'); tender_parameters_json:Mapped[str]=mapped_column(Text,default='[]'); data_status:Mapped[str]=mapped_column(String(32),default='CONFIRMED'); source:Mapped[str]=mapped_column(String(80),default='正式演示数据'); owner:Mapped[str]=mapped_column(String(80),default='产品中心'); last_verified_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); category=relationship(ProductCategory); parameters=relationship('ProductParameter',cascade='all, delete-orphan',order_by='ProductParameter.sort_order'); gallery=relationship('ProductMedia',cascade='all, delete-orphan',order_by='ProductMedia.sort_order'); features=relationship('ProductFeature',cascade='all, delete-orphan',order_by='ProductFeature.sort_order'); variants=relationship('ProductVariant',back_populates='product',cascade='all, delete-orphan',order_by='ProductVariant.sort_order')
class ProductVariant(Base, Timestamped):
    __tablename__='product_variants'; __table_args__=(UniqueConstraint('product_id','model_code',name='uq_product_variant_model'),); id:Mapped[int]=mapped_column(primary_key=True); product_id:Mapped[int]=mapped_column(ForeignKey('products.id',ondelete='CASCADE')); model_code:Mapped[str]=mapped_column(String(100)); material_code:Mapped[str]=mapped_column(String(80),default=''); unit:Mapped[str]=mapped_column(String(24),default='台'); is_primary:Mapped[bool]=mapped_column(Boolean,default=False); is_agent_product:Mapped[bool]=mapped_column(Boolean,default=False); agent_price:Mapped[float|None]=mapped_column(Numeric(14,2),nullable=True); sale_price:Mapped[float|None]=mapped_column(Numeric(14,2),nullable=True); warranty_months:Mapped[int]=mapped_column(Integer,default=12); extended_warranty_rule:Mapped[str]=mapped_column(Text,default=''); applicable_scenes_json:Mapped[str]=mapped_column(Text,default='[]'); sales_notes:Mapped[str]=mapped_column(Text,default=''); commercial_status:Mapped[str]=mapped_column(String(32),default='ACTIVE'); specifications_json:Mapped[str]=mapped_column(Text,default='{}'); sort_order:Mapped[int]=mapped_column(Integer,default=0); product=relationship(Product,back_populates='variants')
class ProductParameter(Base, Timestamped):
    __tablename__='product_parameters'; __table_args__=(UniqueConstraint('product_id','name','group_name',name='uq_product_parameter_name'),); id:Mapped[int]=mapped_column(primary_key=True); product_id:Mapped[int]=mapped_column(ForeignKey('products.id',ondelete='CASCADE')); name:Mapped[str]=mapped_column(String(120)); value:Mapped[str]=mapped_column(Text,default=''); unit:Mapped[str]=mapped_column(String(32),default=''); group_name:Mapped[str]=mapped_column(String(80),default='基础参数'); highlight:Mapped[bool]=mapped_column(Boolean,default=False); data_type:Mapped[str]=mapped_column(String(24),default='TEXT'); sort_order:Mapped[int]=mapped_column(Integer,default=0)
class KnowledgeCommercialProfile(Base, Timestamped):
    __tablename__='knowledge_commercial_profiles'; __table_args__=(UniqueConstraint('center_type','center_id',name='uq_knowledge_commercial_profile'),); id:Mapped[int]=mapped_column(primary_key=True); center_type:Mapped[str]=mapped_column(String(48)); center_id:Mapped[int]=mapped_column(Integer); material_code:Mapped[str]=mapped_column(String(80),default=''); unit:Mapped[str]=mapped_column(String(32),default='套'); is_agent_product:Mapped[bool]=mapped_column(Boolean,default=False); agent_price:Mapped[float|None]=mapped_column(Numeric(14,2),nullable=True); sale_price:Mapped[float|None]=mapped_column(Numeric(14,2),nullable=True); warranty_months:Mapped[int]=mapped_column(Integer,default=12); extended_warranty_rule:Mapped[str]=mapped_column(Text,default=''); applicable_scenes_json:Mapped[str]=mapped_column(Text,default='[]'); sales_notes:Mapped[str]=mapped_column(Text,default=''); commercial_status:Mapped[str]=mapped_column(String(32),default='ACTIVE'); license_unit:Mapped[str]=mapped_column(String(40),default=''); included_quantity:Mapped[int|None]=mapped_column(Integer,nullable=True); overage_unit_price:Mapped[float|None]=mapped_column(Numeric(14,2),nullable=True); delivery_method:Mapped[str]=mapped_column(String(160),default='')
class ProductMedia(Base, Timestamped):
    __tablename__='product_media'; id:Mapped[int]=mapped_column(primary_key=True); product_id:Mapped[int]=mapped_column(ForeignKey('products.id',ondelete='CASCADE')); image:Mapped[str]=mapped_column(String(500)); title:Mapped[str]=mapped_column(String(160),default=''); sort_order:Mapped[int]=mapped_column(Integer,default=0)
class ProductFeature(Base, Timestamped):
    __tablename__='product_features'; id:Mapped[int]=mapped_column(primary_key=True); product_id:Mapped[int]=mapped_column(ForeignKey('products.id',ondelete='CASCADE')); title:Mapped[str]=mapped_column(String(160)); description:Mapped[str]=mapped_column(Text,default=''); icon:Mapped[str]=mapped_column(String(80),default=''); sort_order:Mapped[int]=mapped_column(Integer,default=0)
class Capability(Base, Timestamped):
    __tablename__='capabilities'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(100),unique=True); code:Mapped[str]=mapped_column(String(80),default=''); version:Mapped[str]=mapped_column(String(32),default='v1.0'); category:Mapped[str]=mapped_column(String(80)); function_type:Mapped[str]=mapped_column(String(80),default='识别'); model_type:Mapped[str]=mapped_column(String(80),default='DETECTION'); task_type:Mapped[str]=mapped_column(String(80),default=''); metrics_json:Mapped[str]=mapped_column(Text,default='{}'); input_requirements_json:Mapped[str]=mapped_column(Text,default='{}'); deployment_requirements_json:Mapped[str]=mapped_column(Text,default='{}'); use_conditions_json:Mapped[str]=mapped_column(Text,default='[]'); boundaries_json:Mapped[str]=mapped_column(Text,default='[]'); description:Mapped[str]=mapped_column(Text); status:Mapped[str]=mapped_column(String(32),default='SUPPORTED'); metrics=relationship('ModelMetric',cascade='all, delete-orphan',order_by='ModelMetric.sort_order'); inputs=relationship('ModelInputDefinition',cascade='all, delete-orphan',order_by='ModelInputDefinition.sort_order'); outputs=relationship('ModelOutputDefinition',cascade='all, delete-orphan',order_by='ModelOutputDefinition.sort_order')
class ModelMetric(Base, Timestamped):
    __tablename__='model_metrics'; id:Mapped[int]=mapped_column(primary_key=True); capability_id:Mapped[int]=mapped_column(ForeignKey('capabilities.id',ondelete='CASCADE')); name:Mapped[str]=mapped_column(String(120)); value:Mapped[str]=mapped_column(Text,default=''); unit:Mapped[str]=mapped_column(String(32),default=''); group_name:Mapped[str]=mapped_column(String(80),default='性能指标'); condition:Mapped[str]=mapped_column(Text,default=''); source:Mapped[str]=mapped_column(String(240),default=''); dataset:Mapped[str]=mapped_column(String(200),default=''); sample_count:Mapped[str]=mapped_column(String(80),default=''); input_resolution:Mapped[str]=mapped_column(String(80),default=''); hardware:Mapped[str]=mapped_column(String(160),default=''); runtime:Mapped[str]=mapped_column(String(120),default=''); tested_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); highlight:Mapped[bool]=mapped_column(Boolean,default=False); sort_order:Mapped[int]=mapped_column(Integer,default=0)
class ModelInputDefinition(Base, Timestamped):
    __tablename__='model_input_definitions'; id:Mapped[int]=mapped_column(primary_key=True); capability_id:Mapped[int]=mapped_column(ForeignKey('capabilities.id',ondelete='CASCADE')); name:Mapped[str]=mapped_column(String(120)); data_type:Mapped[str]=mapped_column(String(80)); required:Mapped[bool]=mapped_column(Boolean,default=False); description:Mapped[str]=mapped_column(Text,default=''); example:Mapped[str]=mapped_column(Text,default=''); sort_order:Mapped[int]=mapped_column(Integer,default=0)
class ModelOutputDefinition(Base, Timestamped):
    __tablename__='model_output_definitions'; id:Mapped[int]=mapped_column(primary_key=True); capability_id:Mapped[int]=mapped_column(ForeignKey('capabilities.id',ondelete='CASCADE')); name:Mapped[str]=mapped_column(String(120)); data_type:Mapped[str]=mapped_column(String(80)); description:Mapped[str]=mapped_column(Text,default=''); example:Mapped[str]=mapped_column(Text,default=''); sort_order:Mapped[int]=mapped_column(Integer,default=0)
class Algorithm(Base, Timestamped):
    __tablename__='algorithms'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(120),unique=True); code:Mapped[str]=mapped_column(String(80),default=''); version:Mapped[str]=mapped_column(String(32)); category:Mapped[str]=mapped_column(String(80)); principle:Mapped[str]=mapped_column(Text,default=''); input_summary:Mapped[str]=mapped_column(Text,default=''); output_summary:Mapped[str]=mapped_column(Text,default=''); metrics_json:Mapped[str]=mapped_column(Text,default='{}'); boundaries_json:Mapped[str]=mapped_column(Text,default='[]'); description:Mapped[str]=mapped_column(Text); status:Mapped[str]=mapped_column(String(32),default='SUPPORTED'); parameters=relationship('AlgorithmParameter',cascade='all, delete-orphan',order_by='AlgorithmParameter.sort_order'); metrics=relationship('AlgorithmMetric',cascade='all, delete-orphan',order_by='AlgorithmMetric.sort_order')
class AlgorithmParameter(Base, Timestamped):
    __tablename__='algorithm_parameters'; id:Mapped[int]=mapped_column(primary_key=True); algorithm_id:Mapped[int]=mapped_column(ForeignKey('algorithms.id',ondelete='CASCADE')); name:Mapped[str]=mapped_column(String(120)); value:Mapped[str]=mapped_column(Text,default=''); unit:Mapped[str]=mapped_column(String(32),default=''); group_name:Mapped[str]=mapped_column(String(80),default='核心参数'); sort_order:Mapped[int]=mapped_column(Integer,default=0)
class AlgorithmMetric(Base, Timestamped):
    __tablename__='algorithm_metrics'; id:Mapped[int]=mapped_column(primary_key=True); algorithm_id:Mapped[int]=mapped_column(ForeignKey('algorithms.id',ondelete='CASCADE')); name:Mapped[str]=mapped_column(String(120)); value:Mapped[str]=mapped_column(Text,default=''); unit:Mapped[str]=mapped_column(String(32),default=''); group_name:Mapped[str]=mapped_column(String(80),default='性能指标'); condition:Mapped[str]=mapped_column(Text,default=''); source:Mapped[str]=mapped_column(String(240),default=''); highlight:Mapped[bool]=mapped_column(Boolean,default=False); sort_order:Mapped[int]=mapped_column(Integer,default=0)
class Software(Base, Timestamped):
    __tablename__='software'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(120),unique=True); code:Mapped[str]=mapped_column(String(80),default=''); software_type:Mapped[str]=mapped_column(String(48),default='PLATFORM'); vendor:Mapped[str]=mapped_column(String(120),default='海智科技'); version:Mapped[str]=mapped_column(String(32)); deployment_mode:Mapped[str]=mapped_column(String(48),default='PRIVATE'); supported_os_json:Mapped[str]=mapped_column(Text,default='[]'); database_json:Mapped[str]=mapped_column(Text,default='[]'); protocols_json:Mapped[str]=mapped_column(Text,default='[]'); boundaries_json:Mapped[str]=mapped_column(Text,default='[]'); logo:Mapped[str]=mapped_column(String(500),default=''); detail_description:Mapped[str]=mapped_column(Text,default=''); description:Mapped[str]=mapped_column(Text); status:Mapped[str]=mapped_column(String(32),default='SUPPORTED'); modules=relationship('SoftwareModule',cascade='all, delete-orphan',order_by='SoftwareModule.sort_order'); versions=relationship('SoftwareVersion',cascade='all, delete-orphan',order_by='SoftwareVersion.released_at.desc()'); screenshots=relationship('SoftwareMedia',cascade='all, delete-orphan',order_by='SoftwareMedia.sort_order')
class SoftwareModule(Base, Timestamped):
    __tablename__='software_modules'; id:Mapped[int]=mapped_column(primary_key=True); software_id:Mapped[int]=mapped_column(ForeignKey('software.id',ondelete='CASCADE')); name:Mapped[str]=mapped_column(String(120)); description:Mapped[str]=mapped_column(Text,default=''); icon:Mapped[str]=mapped_column(String(80),default=''); sort_order:Mapped[int]=mapped_column(Integer,default=0); features=relationship('SoftwareFeature',cascade='all, delete-orphan',order_by='SoftwareFeature.sort_order')
class SoftwareFeature(Base, Timestamped):
    __tablename__='software_features'; id:Mapped[int]=mapped_column(primary_key=True); module_id:Mapped[int]=mapped_column(ForeignKey('software_modules.id',ondelete='CASCADE')); name:Mapped[str]=mapped_column(String(160)); description:Mapped[str]=mapped_column(Text,default=''); sort_order:Mapped[int]=mapped_column(Integer,default=0)
class SoftwareVersion(Base, Timestamped):
    __tablename__='software_versions'; id:Mapped[int]=mapped_column(primary_key=True); software_id:Mapped[int]=mapped_column(ForeignKey('software.id',ondelete='CASCADE')); version:Mapped[str]=mapped_column(String(32)); released_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); summary:Mapped[str]=mapped_column(Text,default='')
class SoftwareMedia(Base, Timestamped):
    __tablename__='software_media'; id:Mapped[int]=mapped_column(primary_key=True); software_id:Mapped[int]=mapped_column(ForeignKey('software.id',ondelete='CASCADE')); image:Mapped[str]=mapped_column(String(500)); title:Mapped[str]=mapped_column(String(160),default=''); sort_order:Mapped[int]=mapped_column(Integer,default=0)
class Scene(Base, Timestamped):
    __tablename__='scenes'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(120),unique=True); category:Mapped[str]=mapped_column(String(80),default='水域安全'); summary:Mapped[str]=mapped_column(Text); cover_image:Mapped[str]=mapped_column(String(500),default=''); pain_points:Mapped[str]=mapped_column(Text,default=''); goals_json:Mapped[str]=mapped_column(Text,default='[]'); process_json:Mapped[str]=mapped_column(Text,default='[]'); conditions_json:Mapped[str]=mapped_column(Text,default='[]'); tags_json:Mapped[str]=mapped_column(Text,default='[]'); core_capability_summary:Mapped[str]=mapped_column(Text,default=''); status:Mapped[str]=mapped_column(String(32),default='PUBLISHED'); pains=relationship('ScenePain',cascade='all, delete-orphan',order_by='ScenePain.sort_order'); goals=relationship('SceneGoal',cascade='all, delete-orphan',order_by='SceneGoal.sort_order'); process_steps=relationship('SceneProcessStep',cascade='all, delete-orphan',order_by='SceneProcessStep.sort_order')
class ScenePain(Base, Timestamped):
    __tablename__='scene_pains'; id:Mapped[int]=mapped_column(primary_key=True); scene_id:Mapped[int]=mapped_column(ForeignKey('scenes.id',ondelete='CASCADE')); title:Mapped[str]=mapped_column(String(160)); description:Mapped[str]=mapped_column(Text,default=''); icon:Mapped[str]=mapped_column(String(80),default=''); sort_order:Mapped[int]=mapped_column(Integer,default=0)
class SceneGoal(Base, Timestamped):
    __tablename__='scene_goals'; id:Mapped[int]=mapped_column(primary_key=True); scene_id:Mapped[int]=mapped_column(ForeignKey('scenes.id',ondelete='CASCADE')); title:Mapped[str]=mapped_column(String(160)); description:Mapped[str]=mapped_column(Text,default=''); icon:Mapped[str]=mapped_column(String(80),default=''); sort_order:Mapped[int]=mapped_column(Integer,default=0)
class SceneProcessStep(Base, Timestamped):
    __tablename__='scene_process_steps'; id:Mapped[int]=mapped_column(primary_key=True); scene_id:Mapped[int]=mapped_column(ForeignKey('scenes.id',ondelete='CASCADE')); node_title:Mapped[str]=mapped_column(String(160)); node_description:Mapped[str]=mapped_column(Text,default=''); icon:Mapped[str]=mapped_column(String(80),default=''); sort_order:Mapped[int]=mapped_column(Integer,default=0)
class Solution(Base, Timestamped):
    __tablename__='solutions'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(120),unique=True); code:Mapped[str]=mapped_column(String(80),default=''); category:Mapped[str]=mapped_column(String(80),default='水域安全'); scene_id:Mapped[int]=mapped_column(ForeignKey('scenes.id')); tier:Mapped[str]=mapped_column(String(32)); status:Mapped[str]=mapped_column(String(32),default='ACTIVE'); summary:Mapped[str]=mapped_column(Text); cover_image:Mapped[str]=mapped_column(String(500),default=''); target_description:Mapped[str]=mapped_column(Text,default=''); coverage_scope:Mapped[str]=mapped_column(Text,default=''); architecture_summary:Mapped[str]=mapped_column(Text,default=''); implementation_notes:Mapped[str]=mapped_column(Text,default=''); scene=relationship(Scene); architecture=relationship('SolutionArchitectureNode',cascade='all, delete-orphan',order_by='SolutionArchitectureNode.sort_order'); capability_coverage=relationship('SolutionCapabilityCoverage',cascade='all, delete-orphan',order_by='SolutionCapabilityCoverage.sort_order')
class SolutionArchitectureNode(Base, Timestamped):
    __tablename__='solution_architecture_nodes'; id:Mapped[int]=mapped_column(primary_key=True); solution_id:Mapped[int]=mapped_column(ForeignKey('solutions.id',ondelete='CASCADE')); layer:Mapped[str]=mapped_column(String(100)); name:Mapped[str]=mapped_column(String(160)); description:Mapped[str]=mapped_column(Text,default=''); relation_type:Mapped[str]=mapped_column(String(48),default=''); relation_id:Mapped[int|None]=mapped_column(Integer,nullable=True); sort_order:Mapped[int]=mapped_column(Integer,default=0)
class SolutionCapabilityCoverage(Base, Timestamped):
    __tablename__='solution_capability_coverage'; id:Mapped[int]=mapped_column(primary_key=True); solution_id:Mapped[int]=mapped_column(ForeignKey('solutions.id',ondelete='CASCADE')); capability_name:Mapped[str]=mapped_column(String(160)); status:Mapped[str]=mapped_column(String(32),default='COVERED'); implementation:Mapped[str]=mapped_column(Text,default=''); relation_objects_json:Mapped[str]=mapped_column(Text,default='[]'); notes:Mapped[str]=mapped_column(Text,default=''); sort_order:Mapped[int]=mapped_column(Integer,default=0)
class SolutionBomItem(Base, Timestamped):
    __tablename__='solution_bom_items'; id:Mapped[int]=mapped_column(primary_key=True); solution_id:Mapped[int]=mapped_column(ForeignKey('solutions.id',ondelete='CASCADE')); product_id:Mapped[int]=mapped_column(ForeignKey('products.id')); quantity:Mapped[int]=mapped_column(Integer,default=1); unit:Mapped[str]=mapped_column(String(24),default='台'); purpose:Mapped[str]=mapped_column(String(240),default=''); requirement_level:Mapped[str]=mapped_column(String(24),default='REQUIRED'); recommendation_reason:Mapped[str]=mapped_column(Text,default=''); product=relationship(Product)
class ProductCapability(Base):
    __tablename__='product_capabilities'; product_id:Mapped[int]=mapped_column(ForeignKey('products.id'),primary_key=True); capability_id:Mapped[int]=mapped_column(ForeignKey('capabilities.id'),primary_key=True)
class KnowledgeRelation(Base, Timestamped):
    __tablename__='knowledge_relations'; __table_args__=(UniqueConstraint('source_type','source_id','target_type','target_id','relation_type',name='uq_knowledge_relation'),Index('ix_knowledge_relation_source','source_type','source_id'),Index('ix_knowledge_relation_target','target_type','target_id')); id:Mapped[int]=mapped_column(primary_key=True); source_type:Mapped[str]=mapped_column(String(48)); source_id:Mapped[int]=mapped_column(Integer); target_type:Mapped[str]=mapped_column(String(48)); target_id:Mapped[int]=mapped_column(Integer); relation_type:Mapped[str]=mapped_column(String(48),default='RELATED'); metadata_json:Mapped[str]=mapped_column(Text,default='{}')
class BomRule(Base, Timestamped):
    __tablename__='bom_rules'; id:Mapped[int]=mapped_column(primary_key=True); code:Mapped[str]=mapped_column(String(80),unique=True); name:Mapped[str]=mapped_column(String(160)); rule_type:Mapped[str]=mapped_column(String(32),default='RECOMMEND'); condition_json:Mapped[str]=mapped_column(Text); recommendation_json:Mapped[str]=mapped_column(Text); enabled:Mapped[bool]=mapped_column(Boolean,default=True); current_version:Mapped[int]=mapped_column(Integer,default=1)
class Project(Base, Timestamped):
    __tablename__='projects'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(160)); customer:Mapped[str]=mapped_column(String(160)); region:Mapped[str]=mapped_column(String(100)); sales_owner_id:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'),nullable=True); scene_id:Mapped[int]=mapped_column(ForeignKey('scenes.id')); status:Mapped[str]=mapped_column(String(24),default='DRAFT'); requirements_json:Mapped[str]=mapped_column(Text,default='{}'); bom_json:Mapped[str]=mapped_column(Text,default='[]'); bom_version:Mapped[int]=mapped_column(Integer,default=1); current_requirement_version_id:Mapped[int|None]=mapped_column(Integer,nullable=True); current_bom_version_id:Mapped[int|None]=mapped_column(Integer,nullable=True); notes:Mapped[str]=mapped_column(Text,default=''); created_by:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'),nullable=True); scene=relationship(Scene)
class ProjectRequirementVersion(Base, Timestamped):
    __tablename__='project_requirement_versions'; __table_args__=(UniqueConstraint('project_id','version',name='uq_project_requirement_version'),); id:Mapped[int]=mapped_column(primary_key=True); project_id:Mapped[int]=mapped_column(ForeignKey('projects.id',ondelete='CASCADE')); version:Mapped[int]=mapped_column(Integer); raw_requirement:Mapped[str]=mapped_column(Text,default=''); ai_parsed_json:Mapped[str]=mapped_column(Text,default='{}'); user_adjusted_json:Mapped[str]=mapped_column(Text,default='{}'); confirmed_json:Mapped[str]=mapped_column(Text,default='{}'); confirmed_by:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'),nullable=True); confirmed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class BomRuleVersion(Base, Timestamped):
    __tablename__='bom_rule_versions'; __table_args__=(UniqueConstraint('rule_id','version',name='uq_bom_rule_version'),); id:Mapped[int]=mapped_column(primary_key=True); rule_id:Mapped[int]=mapped_column(ForeignKey('bom_rules.id',ondelete='CASCADE')); version:Mapped[int]=mapped_column(Integer); rule_type:Mapped[str]=mapped_column(String(32)); condition_json:Mapped[str]=mapped_column(Text); action_json:Mapped[str]=mapped_column(Text); enabled:Mapped[bool]=mapped_column(Boolean,default=True); changed_by:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'),nullable=True)
class ProjectBomVersion(Base, Timestamped):
    __tablename__='project_bom_versions'; __table_args__=(UniqueConstraint('project_id','version',name='uq_project_bom_version'),); id:Mapped[int]=mapped_column(primary_key=True); project_id:Mapped[int]=mapped_column(ForeignKey('projects.id',ondelete='CASCADE')); version:Mapped[int]=mapped_column(Integer); requirement_version_id:Mapped[int|None]=mapped_column(ForeignKey('project_requirement_versions.id',ondelete='SET NULL'),nullable=True); source:Mapped[str]=mapped_column(String(32),default='AI_RECOMMEND'); snapshot_json:Mapped[str]=mapped_column(Text,default='[]'); manual_edited:Mapped[bool]=mapped_column(Boolean,default=False); change_summary:Mapped[str]=mapped_column(Text,default=''); created_by:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'),nullable=True)
class BomValidationRun(Base, Timestamped):
    __tablename__='bom_validation_runs'; id:Mapped[int]=mapped_column(primary_key=True); project_id:Mapped[int]=mapped_column(ForeignKey('projects.id',ondelete='CASCADE')); bom_version_id:Mapped[int]=mapped_column(ForeignKey('project_bom_versions.id',ondelete='CASCADE')); run_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); run_by:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'),nullable=True); rule_version_set_json:Mapped[str]=mapped_column(Text,default='[]'); pass_count:Mapped[int]=mapped_column(Integer,default=0); warning_count:Mapped[int]=mapped_column(Integer,default=0); error_count:Mapped[int]=mapped_column(Integer,default=0); result_json:Mapped[str]=mapped_column(Text,default='[]'); override_by:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'),nullable=True); override_reason:Mapped[str]=mapped_column(Text,default=''); override_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class ExcelTemplate(Base, Timestamped):
    __tablename__='excel_templates'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(180)); description:Mapped[str]=mapped_column(Text,default=''); current_version:Mapped[int]=mapped_column(Integer,default=1); enabled:Mapped[bool]=mapped_column(Boolean,default=True); created_by:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'),nullable=True)
class ExcelTemplateVersion(Base, Timestamped):
    __tablename__='excel_template_versions'; __table_args__=(UniqueConstraint('template_id','version',name='uq_excel_template_version'),); id:Mapped[int]=mapped_column(primary_key=True); template_id:Mapped[int]=mapped_column(ForeignKey('excel_templates.id',ondelete='CASCADE')); version:Mapped[int]=mapped_column(Integer); original_file_name:Mapped[str]=mapped_column(String(255)); file_path:Mapped[str]=mapped_column(String(500)); file_hash:Mapped[str]=mapped_column(String(64)); sheet_name:Mapped[str]=mapped_column(String(160),default=''); placeholder_mappings_json:Mapped[str]=mapped_column(Text,default='{}'); bom_template_row:Mapped[int|None]=mapped_column(Integer,nullable=True); bom_column_mappings_json:Mapped[str]=mapped_column(Text,default='{}'); analyzed_json:Mapped[str]=mapped_column(Text,default='{}'); uploaded_by:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'),nullable=True)
class ExportRecord(Base, Timestamped):
    __tablename__='export_records'; id:Mapped[int]=mapped_column(primary_key=True); project_id:Mapped[int]=mapped_column(ForeignKey('projects.id',ondelete='CASCADE')); bom_version_id:Mapped[int]=mapped_column(ForeignKey('project_bom_versions.id')); template_version_id:Mapped[int]=mapped_column(ForeignKey('excel_template_versions.id')); export_by:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'),nullable=True); export_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); file_path:Mapped[str]=mapped_column(String(500)); file_name:Mapped[str]=mapped_column(String(255)); file_hash:Mapped[str]=mapped_column(String(64))
class ProductPrice(Base, Timestamped):
    __tablename__='product_prices'; id:Mapped[int]=mapped_column(primary_key=True); product_id:Mapped[int]=mapped_column(ForeignKey('products.id'),unique=True); reference_price:Mapped[float]=mapped_column(Numeric(12,2)); cost_price:Mapped[float]=mapped_column(Numeric(12,2)); currency:Mapped[str]=mapped_column(String(8),default='CNY'); tax_included:Mapped[bool]=mapped_column(Boolean,default=True); tax_rate:Mapped[float]=mapped_column(Numeric(5,2),default=13); valid_from:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); valid_until:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); notes:Mapped[str]=mapped_column(Text,default=''); product=relationship(Product)
class PriceAccessLog(Base, Timestamped):
    __tablename__='price_access_logs'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); action:Mapped[str]=mapped_column(String(32)); resource:Mapped[str]=mapped_column(String(120))
class Tender(Base, Timestamped):
    __tablename__='tenders'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(180),unique=True); customer:Mapped[str]=mapped_column(String(160)); deadline:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); status:Mapped[str]=mapped_column(String(32),default='PREPARING'); summary:Mapped[str]=mapped_column(Text,default='')
class DocumentAsset(Base, Timestamped):
    __tablename__='documents'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(255)); original_file_name:Mapped[str]=mapped_column(String(255),default=''); path:Mapped[str]=mapped_column(String(500)); mime_type:Mapped[str]=mapped_column(String(100)); file_size:Mapped[int]=mapped_column(Integer,default=0); category:Mapped[str]=mapped_column(String(80),default='产品资料'); version:Mapped[str]=mapped_column(String(32),default='V1.0'); description:Mapped[str]=mapped_column(Text,default=''); status:Mapped[str]=mapped_column(String(24),default='DRAFT'); document_status:Mapped[str]=mapped_column(String(24),default='CURRENT'); applicable_models:Mapped[str]=mapped_column(Text,default=''); applicable_versions:Mapped[str]=mapped_column(Text,default=''); knowledge_enabled:Mapped[bool]=mapped_column(Boolean,default=False); knowledge_status:Mapped[str]=mapped_column(String(24),default='NOT_SYNCED'); knowledge_document_id:Mapped[str]=mapped_column(String(160),default=''); knowledge_dataset_id:Mapped[str]=mapped_column(String(160),default=''); last_knowledge_sync_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); knowledge_sync_error:Mapped[str]=mapped_column(Text,default=''); uploaded_by:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'),nullable=True); product_id:Mapped[int|None]=mapped_column(ForeignKey('products.id'),nullable=True); scene_id:Mapped[int|None]=mapped_column(ForeignKey('scenes.id'),nullable=True); tender_id:Mapped[int|None]=mapped_column(ForeignKey('tenders.id',ondelete='SET NULL'),nullable=True); center_type:Mapped[str|None]=mapped_column(String(48),nullable=True); center_id:Mapped[int|None]=mapped_column(Integer,nullable=True)
class DocumentPreview(Base, Timestamped):
    __tablename__='document_previews'; id:Mapped[int]=mapped_column(primary_key=True); document_id:Mapped[int]=mapped_column(ForeignKey('documents.id',ondelete='CASCADE')); preview_type:Mapped[str]=mapped_column(String(24)); file_path:Mapped[str]=mapped_column(String(500)); mime_type:Mapped[str]=mapped_column(String(100)); status:Mapped[str]=mapped_column(String(24),default='READY'); error_message:Mapped[str]=mapped_column(Text,default='')
class DocumentKnowledgeSync(Base, Timestamped):
    __tablename__='document_knowledge_syncs'; id:Mapped[int]=mapped_column(primary_key=True); document_id:Mapped[int]=mapped_column(ForeignKey('documents.id',ondelete='CASCADE')); status:Mapped[str]=mapped_column(String(24)); requested_by:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'),nullable=True); started_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); finished_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); dataset_id:Mapped[str]=mapped_column(String(160),default=''); external_document_id:Mapped[str]=mapped_column(String(160),default=''); error_message:Mapped[str]=mapped_column(Text,default='')
class KnowledgeImage(Base, Timestamped):
    __tablename__='knowledge_images'; id:Mapped[int]=mapped_column(primary_key=True); public_id:Mapped[str]=mapped_column(String(64),unique=True,index=True); name:Mapped[str]=mapped_column(String(255)); path:Mapped[str]=mapped_column(String(500)); mime_type:Mapped[str]=mapped_column(String(100)); uploaded_by:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'),nullable=True)
class DirectorySyncRun(Base, Timestamped):
    __tablename__='directory_sync_runs'; id:Mapped[int]=mapped_column(primary_key=True); provider:Mapped[str]=mapped_column(String(32),default='AD'); status:Mapped[str]=mapped_column(String(24)); created_count:Mapped[int]=mapped_column(Integer,default=0); updated_count:Mapped[int]=mapped_column(Integer,default=0); disabled_count:Mapped[int]=mapped_column(Integer,default=0); error_message:Mapped[str]=mapped_column(Text,default=''); initiated_by:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'),nullable=True); finished_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class DirectorySyncCandidate(Base, Timestamped):
    __tablename__='directory_sync_candidates'; __table_args__=(UniqueConstraint('run_id','external_id',name='uq_directory_candidate_external'),); id:Mapped[int]=mapped_column(primary_key=True); run_id:Mapped[int]=mapped_column(ForeignKey('directory_sync_runs.id',ondelete='CASCADE')); external_id:Mapped[str]=mapped_column(String(255)); username:Mapped[str]=mapped_column(String(64)); display_name:Mapped[str]=mapped_column(String(80),default=''); email:Mapped[str]=mapped_column(String(160),default=''); department:Mapped[str]=mapped_column(String(160),default=''); distinguished_name:Mapped[str]=mapped_column(String(500),default=''); change_type:Mapped[str]=mapped_column(String(24),default='CREATE'); approval_status:Mapped[str]=mapped_column(String(24),default='PENDING'); role_code:Mapped[str]=mapped_column(String(64),default='sales')
class DirectoryConfig(Base, Timestamped):
    __tablename__='directory_configs'; id:Mapped[int]=mapped_column(primary_key=True); enabled:Mapped[bool]=mapped_column(Boolean,default=False); server_type:Mapped[str]=mapped_column(String(48),default='MS_ACTIVE_DIRECTORY'); protocol:Mapped[str]=mapped_column(String(12),default='LDAP'); host:Mapped[str]=mapped_column(String(255),default=''); port:Mapped[int]=mapped_column(Integer,default=389); timeout_seconds:Mapped[int]=mapped_column(Integer,default=30); bind_dn:Mapped[str]=mapped_column(String(500),default=''); bind_password_encrypted:Mapped[str]=mapped_column(Text,default=''); base_dn:Mapped[str]=mapped_column(String(500),default=''); login_domain:Mapped[str]=mapped_column(String(255),default=''); user_filter:Mapped[str]=mapped_column(String(500),default='(&(objectClass=user)(sAMAccountName=*))'); default_role:Mapped[str]=mapped_column(String(64),default='sales'); last_test_status:Mapped[str]=mapped_column(String(24),default='UNTESTED'); last_test_message:Mapped[str]=mapped_column(String(500),default=''); last_test_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class AiInteractionLog(Base, Timestamped):
    __tablename__='ai_interaction_logs'; id:Mapped[int]=mapped_column(primary_key=True); request_id:Mapped[str]=mapped_column(String(64),unique=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); provider:Mapped[str]=mapped_column(String(32)); model_id:Mapped[str]=mapped_column(String(160)); latency_ms:Mapped[int]=mapped_column(Integer); success:Mapped[bool]=mapped_column(Boolean); failure_reason:Mapped[str]=mapped_column(Text,default='')
class AuditLog(Base, Timestamped):
    __tablename__='audit_logs'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); action:Mapped[str]=mapped_column(String(32)); resource_type:Mapped[str]=mapped_column(String(64)); resource_id:Mapped[str]=mapped_column(String(64)); detail_json:Mapped[str]=mapped_column(Text,default='{}')
class DocumentChunk(Base, Timestamped):
    __tablename__='document_chunks'; id:Mapped[int]=mapped_column(primary_key=True); document_id:Mapped[int|None]=mapped_column(ForeignKey('documents.id',ondelete='CASCADE'),nullable=True); content:Mapped[str]=mapped_column(Text); embedding_json:Mapped[str]=mapped_column(Text); metadata_json:Mapped[str]=mapped_column(Text,default='{}')
class TrainingCourse(Base, Timestamped):
    __tablename__='training_courses'; id:Mapped[int]=mapped_column(primary_key=True); external_course_id:Mapped[str]=mapped_column(String(80),unique=True); name:Mapped[str]=mapped_column(String(180)); summary:Mapped[str]=mapped_column(Text,default=''); launch_url:Mapped[str]=mapped_column(String(500)); status:Mapped[str]=mapped_column(String(32),default='ACTIVE')
