<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { House, Box, Cpu, Connection, MapLocation, Tickets, MagicStick, DocumentChecked, Files, Reading, Setting, Search, Plus, ArrowRight } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
type User={username:string,displayName:string,role:string,permissions:string[]}; type Product={id:number,name:string,modelCode:string,categoryId:number,category:string,summary:string,status:string,dataStatus:string};
const route=useRoute(), router=useRouter()
const token=ref(localStorage.hzToken||''), user=ref<User|null>(null), page=ref('home'), loginForm=ref({username:'',password:''}), products=ref<Product[]>([]), productCategories=ref<any[]>([]), metrics=ref<Record<string,number>>({}), catalog=ref<any[]>([]), projects=ref<any[]>([]), prices=ref<any[]>([]), documents=ref<any[]>([]), tenders=ref<any[]>([]), auditLogs=ref<any[]>([]), courses=ref<any[]>([]), query=ref(''), loading=ref(false), loginError=ref(''), activeProduct=ref<any>(null), activeScene=ref<any>(null), bom=ref<any[]>([]), bomInput=ref({scene:'桥梁防撞',upstream_km:3,downstream_km:3,ptz_count:4,ais:true,yaw:true,ocr:true,overheight:false,vhf:false}), ai=ref('')
const productDialog=ref(false), productSaving=ref(false), editingProductId=ref<number|null>(null), productForm=ref({name:'',model_code:'',category_id:null as number|null,summary:'',status:'ON_SALE'})
const nav=[['home','首页',House],['products','产品中心',Box],['software','软件中心',Cpu],['algorithms','算法中心',Connection],['model-capabilities','模型能力中心',Connection],['scenes','场景中心',MapLocation],['solutions','方案中心',Tickets]]
const navPermission:Record<string,string>={products:'KNOWLEDGE_VIEW',software:'KNOWLEDGE_VIEW',algorithms:'KNOWLEDGE_VIEW','model-capabilities':'KNOWLEDGE_VIEW',scenes:'KNOWLEDGE_VIEW',solutions:'KNOWLEDGE_VIEW'}
const catalogEditPermission:Record<string,string>={software:'KNOWLEDGE_MANAGE',algorithms:'KNOWLEDGE_MANAGE','model-capabilities':'KNOWLEDGE_MANAGE',scenes:'KNOWLEDGE_MANAGE',solutions:'KNOWLEDGE_MANAGE'}
const can=(p:string)=>user.value?.permissions.includes(p)||false; const displayNav=computed(()=>nav.filter(n=>!navPermission[n[0] as string]||can(navPermission[n[0] as string])))
const catalogDialog=ref(false), catalogSaving=ref(false), editingCatalogId=ref<number|null>(null), sceneOptions=ref<any[]>([]), catalogForm=ref({name:'',summary:'',version:'v1.0',category:'通用',scene_id:null as number|null,tier:'标准型',status:'SUPPORTED'})
const projectDialog=ref(false), projectSaving=ref(false), projectDetail=ref<any>(null), projectForm=ref({name:'',customer:'',region:'',scene_id:null as number|null})
const documentDialog=ref(false), documentSaving=ref(false), documentFile=ref<File|null>(null), documentForm=ref({product_id:null as number|null,scene_id:null as number|null,tender_id:null as number|null})
const tenderDialog=ref(false), tenderSaving=ref(false), editingTenderId=ref<number|null>(null), tenderDetail=ref<any>(null), tenderForm=ref({name:'',customer:'',deadline:'',status:'PREPARING',summary:''})
async function api(url:string,opt:any={}){const isForm=opt.body instanceof FormData;const headers={...(isForm?{}:{'Content-Type':'application/json'}),...(token.value?{Authorization:'Bearer '+token.value}:{}),...(opt.headers||{})};const r=await fetch(url,{...opt,headers});const d=r.status===204?null:await r.json();if(!r.ok)throw Error(d?.detail||'请求失败');return d}
async function signIn(){loginError.value='';try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify(loginForm.value)});token.value=d.access_token;localStorage.hzToken=token.value;user.value=d.user;await loadHome()}catch(e:any){loginError.value=e.message}}
function logout(){localStorage.removeItem('hzToken');token.value='';user.value=null}
async function loadHome(){loading.value=true;page.value='home';activeProduct.value=null;catalog.value=[];try{metrics.value=(await api('/api/dashboard')).metrics;products.value=can('KNOWLEDGE_VIEW')?await api('/api/products'):[]}finally{loading.value=false}}
async function loadProductCategories(){if(!productCategories.value.length)productCategories.value=await api('/api/product-categories')}
async function loadPage(key:string){page.value=key;activeProduct.value=null;activeScene.value=null;catalog.value=[];if(key==='home')return loadHome();if(key==='products'){await loadProductCategories();products.value=await api('/api/products?q='+encodeURIComponent(query.value));return}if(['software','algorithms','model-capabilities','scenes','solutions'].includes(key)){catalog.value=await api('/api/catalog/'+key);return}}
async function go(key:string){const path=key==='home'?'/':'/'+key;if(route.path!==path)await router.push(path);await loadPage(key)}
async function viewProduct(p:Product){activeProduct.value=await api('/api/products/'+p.id);page.value='product-detail';await router.push('/products/'+p.id)}
async function viewScene(row:any){activeScene.value=await api('/api/scenes/'+row.id);page.value='scene-detail';await router.push('/scenes/'+row.id)}
async function openCreateProduct(){await loadProductCategories();editingProductId.value=null;productForm.value={name:'',model_code:'',category_id:productCategories.value[0]?.id||null,summary:'',status:'ON_SALE'};productDialog.value=true}
async function openEditProduct(){await loadProductCategories();editingProductId.value=activeProduct.value.id;productForm.value={name:activeProduct.value.name,model_code:activeProduct.value.modelCode,category_id:activeProduct.value.categoryId,summary:activeProduct.value.summary,status:activeProduct.value.status};productDialog.value=true}
async function saveProduct(){if(!productForm.value.name.trim()||!productForm.value.category_id)return ElMessage.warning('请完整填写产品名称和分类');productSaving.value=true;try{if(editingProductId.value){await api('/api/admin/products/'+editingProductId.value,{method:'PATCH',body:JSON.stringify({name:productForm.value.name,summary:productForm.value.summary,status:productForm.value.status})});activeProduct.value=await api('/api/products/'+editingProductId.value)}else{await api('/api/admin/products',{method:'POST',body:JSON.stringify(productForm.value)});await go('products')}productDialog.value=false;ElMessage.success('产品已保存')}finally{productSaving.value=false}}
async function deleteProduct(){await ElMessageBox.confirm('删除后不可恢复，确认删除该产品？','删除产品',{type:'warning'});await api('/api/admin/products/'+activeProduct.value.id,{method:'DELETE'});ElMessage.success('产品已删除');await go('products')}
async function openCreateCatalog(){editingCatalogId.value=null;catalogForm.value={name:'',summary:'',version:'v1.0',category:'通用',scene_id:null,tier:'标准型',status:'SUPPORTED'};if(page.value==='solutions'){sceneOptions.value=await api('/api/catalog/scenes');catalogForm.value.scene_id=sceneOptions.value[0]?.id||null}catalogDialog.value=true}
async function openEditCatalog(row:any){editingCatalogId.value=row.id;catalogForm.value={name:row.name,summary:row.summary||'',version:row.version||'v1.0',category:row.category||'通用',scene_id:row.sceneId||null,tier:row.tier||'标准型',status:row.status||'SUPPORTED'};if(page.value==='solutions')sceneOptions.value=await api('/api/catalog/scenes');catalogDialog.value=true}
async function saveCatalog(){if(!catalogForm.value.name.trim())return ElMessage.warning('请输入名称');catalogSaving.value=true;try{const url=editingCatalogId.value?'/api/admin/catalog/'+page.value+'/'+editingCatalogId.value:'/api/admin/catalog/'+page.value;await api(url,{method:editingCatalogId.value?'PATCH':'POST',body:JSON.stringify(catalogForm.value)});catalogDialog.value=false;await go(page.value);ElMessage.success('知识条目已保存')}finally{catalogSaving.value=false}}
async function deleteCatalog(row:any){await ElMessageBox.confirm('确认删除该知识条目？','删除条目',{type:'warning'});await api('/api/admin/catalog/'+page.value+'/'+row.id,{method:'DELETE'});await go(page.value);ElMessage.success('知识条目已删除')}
async function openSaveProject(){if(!bom.value.length)return ElMessage.warning('请先生成BOM');sceneOptions.value=await api('/api/catalog/scenes');projectForm.value={name:'',customer:'',region:'',scene_id:sceneOptions.value.find(x=>x.name===bomInput.value.scene)?.id||sceneOptions.value[0]?.id||null};projectDialog.value=true}
async function saveProject(){if(!projectForm.value.name||!projectForm.value.customer||!projectForm.value.scene_id)return ElMessage.warning('请完整填写项目名称、客户和场景');projectSaving.value=true;try{await api('/api/projects',{method:'POST',body:JSON.stringify({...projectForm.value,requirements_json:bomInput.value,bom_json:bom.value})});projectDialog.value=false;ElMessage.success('项目配单已保存');await go('projects')}finally{projectSaving.value=false}}
async function openProject(row:any){projectDetail.value=await api('/api/projects/'+row.id)}
async function deleteProject(){await ElMessageBox.confirm('确认删除该项目配单？','删除项目',{type:'warning'});await api('/api/projects/'+projectDetail.value.id,{method:'DELETE'});projectDetail.value=null;await go('projects');ElMessage.success('项目已删除')}
async function exportPrices(){const r=await fetch('/api/prices/export',{headers:{Authorization:'Bearer '+token.value}});if(!r.ok)throw Error('导出失败');const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='haizhi-prices.csv';a.click();URL.revokeObjectURL(url);ElMessage.success('价格表已导出')}
async function openDocumentUpload(){products.value=await api('/api/products');sceneOptions.value=await api('/api/catalog/scenes');tenders.value=can('TENDER_VIEW')?await api('/api/tenders'):[];documentFile.value=null;documentForm.value={product_id:null,scene_id:null,tender_id:null};documentDialog.value=true}
function chooseDocument(event:Event){documentFile.value=(event.target as HTMLInputElement).files?.[0]||null}
async function uploadDocument(){if(!documentFile.value)return ElMessage.warning('请选择文件');documentSaving.value=true;try{const body=new FormData();body.append('file',documentFile.value);for(const [key,value] of Object.entries(documentForm.value))if(value)body.append(key,String(value));await api('/api/documents',{method:'POST',body});documentDialog.value=false;documents.value=await api('/api/documents');ElMessage.success('资料已上传')}finally{documentSaving.value=false}}
async function downloadDocument(row:any){const r=await fetch('/api/documents/'+row.id+'/download',{headers:{Authorization:'Bearer '+token.value}});if(!r.ok)throw Error('下载失败');const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=row.name;a.click();URL.revokeObjectURL(url)}
async function deleteDocument(row:any){await ElMessageBox.confirm('确认删除该资料及其存储对象？','删除资料',{type:'warning'});await api('/api/documents/'+row.id,{method:'DELETE'});documents.value=await api('/api/documents');ElMessage.success('资料已删除')}
function openCreateTender(){editingTenderId.value=null;tenderForm.value={name:'',customer:'',deadline:'',status:'PREPARING',summary:''};tenderDialog.value=true}
function openEditTender(row:any){editingTenderId.value=row.id;tenderForm.value={name:row.name,customer:row.customer,deadline:row.deadline?.slice(0,16)||'',status:row.status,summary:row.summary||''};tenderDialog.value=true}
async function saveTender(){if(!tenderForm.value.name.trim()||!tenderForm.value.customer.trim())return ElMessage.warning('请填写项目名称和客户');tenderSaving.value=true;try{const body={...tenderForm.value,deadline:tenderForm.value.deadline||null};await api(editingTenderId.value?'/api/tenders/'+editingTenderId.value:'/api/tenders',{method:editingTenderId.value?'PATCH':'POST',body:JSON.stringify(body)});tenderDialog.value=false;await go('tenders');ElMessage.success('招投标项目已保存')}finally{tenderSaving.value=false}}
async function openTender(row:any){tenderDetail.value=await api('/api/tenders/'+row.id)}
async function deleteTender(row:any){await ElMessageBox.confirm('删除项目后，已上传资料将保留并解除关联。','删除招投标项目',{type:'warning'});await api('/api/tenders/'+row.id,{method:'DELETE'});tenderDetail.value=null;await go('tenders');ElMessage.success('招投标项目已删除')}
async function runBom(){const d=await api('/api/bom/recommend',{method:'POST',body:JSON.stringify(bomInput.value)});bom.value=d.items}
async function askAi(){ai.value='正在分析需求...';const d=await api('/api/ai/requirement-analysis',{method:'POST',body:JSON.stringify(bomInput.value)});ai.value=d.content}
async function loadCurrentRoute(){
 const name=String(route.name||'home'), id=Number(route.params.id)
 if(name==='products-detail'&&id){activeProduct.value=await api('/api/products/'+id);page.value='product-detail';return}
 if(name==='scenes-detail'&&id){activeScene.value=await api('/api/scenes/'+id);page.value='scene-detail';return}
 await loadPage(name.replace(/-detail$/,''))
}
watch(()=>route.fullPath,()=>{if(token.value&&user.value)loadCurrentRoute()})
onMounted(async()=>{if(token.value){try{user.value=await api('/api/auth/me');await loadCurrentRoute()}catch{logout()}}})
</script>
<template>
 <main v-if="!token" class="login"><el-card class="login-card"><div class="brand"><div class="brand-mark">海</div><b>海智产品中心</b></div><h1>产品知识与售前业务工作台</h1><p>统一管理产品、能力、方案与项目配单</p><el-alert v-if="loginError" :title="loginError" type="error" :closable="false" show-icon/><el-form @submit.prevent="signIn"><el-form-item label="账号"><el-input v-model="loginForm.username" autocomplete="username"/></el-form-item><el-form-item label="密码"><el-input v-model="loginForm.password" type="password" show-password autocomplete="current-password"/></el-form-item><el-button type="primary" native-type="submit" style="width:100%" @click="signIn">登录产品中心</el-button></el-form></el-card></main>
 <main v-else class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">海</div><b>海智产品中心</b></div><div class="nav-title">业务工作台</div><el-menu :default-active="page" @select="go"><el-menu-item v-for="item in displayNav" :key="item[0]" :index="item[0]"><el-icon><component :is="item[2]"/></el-icon><span>{{item[1]}}</span></el-menu-item></el-menu></aside>
 <section class="workspace"><header class="header"><div class="header-left"><span class="crumb">产品知识与售前业务工作台</span><el-input class="header-search" :prefix-icon="Search" placeholder="搜索产品、型号、能力、算法、场景"/></div><div class="user"><el-avatar style="background:#146EF5">{{user?.displayName?.slice(0,1)}}</el-avatar><span><b>{{user?.displayName}}</b><small class="muted"> · {{user?.role}}</small></span><el-button text @click="logout">退出</el-button></div></header>
 <div class="content" v-loading="loading">
  <template v-if="page==='home'"><div class="page-head"><div><h1>欢迎回来，{{user?.displayName}}</h1><p>从六大知识中心开始今天的工作。</p></div><el-button v-if="can('KNOWLEDGE_MANAGE')" type="primary" :icon="Plus" @click="openCreateProduct">新增产品</el-button></div><div class="main-grid" v-if="can('KNOWLEDGE_VIEW')"><section class="card ai-panel"><h2>六大知识中心</h2><p>统一浏览产品、软件、算法、模型能力、场景与方案知识。</p><div style="display:flex;gap:10px;margin-top:12px"><el-button type="primary" @click="go('products')">进入产品中心</el-button><el-button @click="go('scenes')">从场景开始</el-button></div></section><section class="card ai-panel"><h2>常用入口</h2><p>快速进入知识工作区。</p><el-button text @click="go('products')">产品中心 <el-icon><ArrowRight/></el-icon></el-button><el-button text @click="go('model-capabilities')">模型能力中心 <el-icon><ArrowRight/></el-icon></el-button><el-button text @click="go('solutions')">方案中心 <el-icon><ArrowRight/></el-icon></el-button></section></div><div class="metric-grid" style="margin-top:18px"><div v-for="(v,k) in metrics" :key="k" class="card metric"><span class="value">{{v}}</span><span class="label">{{({products:'产品数量',algorithms:'算法数量',capabilities:'模型能力数量',scenes:'标准场景',solutions:'方案数量',projects:'项目数量'} as any)[k]}}</span></div></div><template v-if="can('KNOWLEDGE_VIEW')"><h2 class="section-title">核心产品</h2><div class="product-grid"><article v-for="p in products.slice(0,4)" :key="p.id" class="card product-card" @click="viewProduct(p)"><div class="product-icon"><el-icon><Box/></el-icon></div><h3>{{p.name}}</h3><p>{{p.summary}}</p><span class="status">在售 · {{p.modelCode}}</span></article></div></template></template>
  <template v-else-if="page==='products'"><div class="page-head"><div><h1>产品中心</h1><p>统一管理公司产品、型号、技术参数及模型能力关系。</p></div><el-button v-if="can('KNOWLEDGE_MANAGE')" type="primary" :icon="Plus" @click="openCreateProduct">新增产品</el-button></div><div class="toolbar"><el-input v-model="query" placeholder="搜索产品或型号" :prefix-icon="Search" clearable @keyup.enter="go('products')"/><el-button @click="go('products')">查询</el-button></div><div class="product-grid"><article v-for="p in products" :key="p.id" class="card product-card" @click="viewProduct(p)"><div class="product-icon"><el-icon><Box/></el-icon></div><h3>{{p.name}}</h3><p>{{p.summary}}</p><span class="status">在售 · {{p.category}}</span><div class="muted" style="margin-top:8px">{{p.modelCode}}</div></article></div><section v-if="!products.length" class="card empty"><el-icon size="36"><Search/></el-icon><p>未找到匹配产品</p></section></template>
  <template v-else-if="page==='product-detail'&&activeProduct"><div class="page-head"><div><h1>产品详情</h1><p>产品知识门户与关联模型能力信息。</p></div><div><el-button v-if="can('KNOWLEDGE_MANAGE')" @click="openEditProduct">编辑</el-button><el-button v-if="can('KNOWLEDGE_MANAGE')" type="danger" plain @click="deleteProduct">删除</el-button><el-button @click="go('products')">返回列表</el-button></div></div><section class="card detail-hero"><div class="detail-icon"><el-icon><Box/></el-icon></div><div><h2>{{activeProduct.name}}</h2><p>{{activeProduct.summary}}</p><div style="margin-top:12px"><el-tag type="success">在售</el-tag><el-tag style="margin-left:8px">{{activeProduct.modelCode}}</el-tag></div></div></section><el-tabs style="margin-top:18px"><el-tab-pane label="产品概览"><el-descriptions :column="2" border><el-descriptions-item label="分类">{{activeProduct.category}}</el-descriptions-item><el-descriptions-item label="数据状态">已确认</el-descriptions-item><el-descriptions-item label="数据来源">{{activeProduct.source}}</el-descriptions-item><el-descriptions-item label="责任人">{{activeProduct.owner}}</el-descriptions-item></el-descriptions></el-tab-pane><el-tab-pane label="技术参数"><el-descriptions :column="1" border><el-descriptions-item v-for="(v,k) in activeProduct.parameters" :key="k" :label="k">{{v}}</el-descriptions-item></el-descriptions></el-tab-pane><el-tab-pane label="模型能力"><div v-if="activeProduct.capabilities?.length" class="catalog-grid"><article v-for="cap in activeProduct.capabilities" :key="cap.id" class="card product-card"><h3>{{cap.name}}</h3><p>{{cap.category}}</p></article></div><div v-else class="empty">暂无关联模型能力</div></el-tab-pane><el-tab-pane v-if="can('PRICE_VIEW')" label="价格信息">价格信息随产品展示。</el-tab-pane></el-tabs></template>
  <template v-else-if="['software','algorithms','model-capabilities','scenes','solutions'].includes(page)"><div class="page-head"><div><h1>{{({software:'软件中心',algorithms:'算法中心','model-capabilities':'模型能力中心',scenes:'场景中心',solutions:'方案中心'} as any)[page]}}</h1><p>以独立实体管理产品知识和业务关系。</p></div><el-button v-if="can(catalogEditPermission[page])" type="primary" :icon="Plus" @click="openCreateCatalog">新增条目</el-button></div><div class="catalog-grid"><article v-for="x in catalog" :key="x.id" class="card product-card" @click="page==='scenes'&&viewScene(x)"><div class="product-icon"><el-icon><Connection/></el-icon></div><h3>{{x.name}}</h3><p>{{x.summary}}</p><div class="muted" v-if="x.version||x.category||x.scene">{{[x.version,x.category,x.scene,x.tier].filter(Boolean).join(' · ')}}</div><span class="status">正式支持</span><div v-if="can(catalogEditPermission[page])" style="margin-top:12px"><el-button size="small" @click.stop="openEditCatalog(x)">编辑</el-button><el-button size="small" type="danger" plain @click.stop="deleteCatalog(x)">删除</el-button></div></article></div><section v-if="!catalog.length" class="card empty"><el-icon size="36"><Files/></el-icon><p>暂无知识条目</p></section></template>
  <template v-else-if="page==='scene-detail'&&activeScene"><div class="page-head"><div><h1>{{activeScene.name}}</h1><p>{{activeScene.summary}}</p></div><el-button @click="go('scenes')">返回场景中心</el-button></div><section class="card"><h2>业务痛点</h2><p>{{activeScene.painPoints||'暂无业务痛点说明'}}</p></section><h2 class="section-title">关联方案</h2><div class="catalog-grid"><article v-for="solution in activeScene.solutions" :key="solution.id" class="card product-card"><div class="product-icon"><el-icon><Tickets/></el-icon></div><h3>{{solution.name}}</h3><p>{{solution.summary}}</p><span class="status">{{solution.tier}}</span></article></div><section v-if="!activeScene.solutions.length" class="card empty"><p>暂无关联方案</p></section></template>
  <template v-else-if="page==='bom'"><div class="page-head"><div><h1>智能配单</h1><p>需求解析、规则校验与BOM编辑在同一业务流程中完成。</p></div><div><el-button :disabled="!bom.length" @click="openSaveProject">保存项目</el-button><el-button type="primary" @click="askAi">AI分析需求</el-button></div></div><el-steps :active="bom.length?5:2" finish-status="success" style="margin-bottom:18px"><el-step title="需求输入"/><el-step title="需求解析"/><el-step title="关键条件"/><el-step title="推荐方案"/><el-step title="BOM编辑"/><el-step title="保存导出"/></el-steps><div class="bom-grid"><section class="card bom-panel"><h3>项目条件</h3><el-form label-position="top"><el-form-item label="场景"><el-input v-model="bomInput.scene"/></el-form-item><el-form-item label="球机数量"><el-input-number v-model="bomInput.ptz_count" :min="0"/></el-form-item><el-checkbox v-model="bomInput.ais">AIS融合</el-checkbox><el-checkbox v-model="bomInput.yaw">偏航预警</el-checkbox><el-checkbox v-model="bomInput.ocr">船名OCR</el-checkbox><el-checkbox v-model="bomInput.overheight">超高预警</el-checkbox><el-checkbox v-model="bomInput.vhf">VHF通信</el-checkbox></el-form><el-button type="primary" style="margin-top:18px" @click="runBom">生成BOM</el-button></section><section class="card bom-panel"><h3>当前BOM</h3><el-table :data="bom"><el-table-column prop="name" label="产品"/><el-table-column prop="model" label="型号"/><el-table-column prop="quantity" label="数量"><template #default="s"><el-input-number v-model="s.row.quantity" :min="1"/></template></el-table-column><el-table-column prop="reason" label="推荐原因"/></el-table></section><section class="card bom-panel"><h3>规则校验</h3><div class="rule-pass">PASS · 核心能力覆盖完整</div><ul><li v-for="item in bom" :key="item.model">{{item.reason}}</li></ul><el-alert v-if="ai" :title="ai" type="info" :closable="false"/></section></div></template>
  <template v-else-if="page==='projects'"><div class="page-head"><div><h1>项目配单</h1><p>已保存项目的需求条件、所属场景与 BOM 版本。</p></div><el-button type="primary" :icon="Plus" @click="go('bom')">新建项目配单</el-button></div><el-table :data="projects" class="card" @row-click="openProject"><el-table-column prop="name" label="项目名称" min-width="180"/><el-table-column prop="customer" label="客户" min-width="140"/><el-table-column prop="region" label="区域"/><el-table-column prop="scene" label="应用场景"/><el-table-column prop="bomVersion" label="BOM版本"><template #default="s">V{{s.row.bomVersion}}</template></el-table-column><el-table-column prop="updatedAt" label="最近更新"><template #default="s">{{new Date(s.row.updatedAt).toLocaleString()}}</template></el-table-column></el-table><section v-if="!projects.length" class="card empty"><p>暂无已保存项目配单</p></section></template>
  <template v-else-if="page==='prices'"><div class="page-head"><div><h1>价格查询</h1><p>仅向具备价格权限的角色展示，所有访问均纳入审计。</p></div><el-button v-if="can('PRICE_EXPORT')" @click="exportPrices">导出价格表</el-button></div><el-table :data="prices" class="card"><el-table-column prop="product" label="产品名称" min-width="180"/><el-table-column prop="modelCode" label="型号"/><el-table-column prop="referencePrice" label="参考报价"><template #default="s">{{s.row.currency}} {{Number(s.row.referencePrice).toLocaleString()}}</template></el-table-column><el-table-column v-if="prices.some(x=>x.costPrice!==null)" prop="costPrice" label="成本价"><template #default="s">{{s.row.costPrice===null?'无权限':s.row.currency+' '+Number(s.row.costPrice).toLocaleString()}}</template></el-table-column></el-table></template>
  <template v-else-if="page==='documents'"><div class="page-head"><div><h1>资料中心</h1><p>产品资料、场景附件和投标文件统一归档。</p></div><el-button v-if="can('DOCUMENT_EDIT')" type="primary" :icon="Plus" @click="openDocumentUpload">上传资料</el-button></div><el-table :data="documents" class="card"><el-table-column prop="name" label="文件名称" min-width="220"/><el-table-column prop="mimeType" label="类型" min-width="130"/><el-table-column label="业务关联" min-width="180"><template #default="s"><span v-if="s.row.productId">产品 #{{s.row.productId}}</span><span v-else-if="s.row.sceneId">场景 #{{s.row.sceneId}}</span><span v-else-if="s.row.tenderId">投标 #{{s.row.tenderId}}</span><span v-else class="muted">通用资料</span></template></el-table-column><el-table-column prop="updatedAt" label="上传时间" min-width="170"><template #default="s">{{new Date(s.row.updatedAt).toLocaleString()}}</template></el-table-column><el-table-column label="操作" width="160" fixed="right"><template #default="s"><el-button link type="primary" @click="downloadDocument(s.row)">下载</el-button><el-button v-if="can('DOCUMENT_EDIT')" link type="danger" @click="deleteDocument(s.row)">删除</el-button></template></el-table-column></el-table><section v-if="!documents.length" class="card empty"><el-icon size="36"><Files/></el-icon><p>暂无资料</p></section></template>
  <template v-else-if="page==='tenders'"><div class="page-head"><div><h1>招投标工作台</h1><p>跟踪投标项目、交付节点与关联文件。</p></div><el-button v-if="can('TENDER_EDIT')" type="primary" :icon="Plus" @click="openCreateTender">新建投标项目</el-button></div><el-table :data="tenders" class="card" @row-click="openTender"><el-table-column prop="name" label="项目名称" min-width="220"/><el-table-column prop="customer" label="客户" min-width="150"/><el-table-column label="状态" width="120"><template #default="s"><el-tag :type="s.row.status==='SUBMITTED'?'success':s.row.status==='CLOSED'?'info':'warning'">{{({PREPARING:'编制中',SUBMITTED:'已提交',CLOSED:'已结束'} as any)[s.row.status]||s.row.status}}</el-tag></template></el-table-column><el-table-column prop="deadline" label="截止时间" min-width="170"><template #default="s">{{s.row.deadline?new Date(s.row.deadline).toLocaleString():'未设置'}}</template></el-table-column><el-table-column prop="documentCount" label="关联资料" width="100"/><el-table-column label="操作" width="150"><template #default="s"><el-button link type="primary" @click.stop="openTender(s.row)">查看</el-button><el-button v-if="can('TENDER_EDIT')" link @click.stop="openEditTender(s.row)">编辑</el-button></template></el-table-column></el-table><section v-if="!tenders.length" class="card empty"><el-icon size="36"><Tickets/></el-icon><p>暂无招投标项目</p></section></template>
  <template v-else-if="page==='admin'"><div class="page-head"><div><h1>系统管理</h1><p>查看关键业务变更审计记录，支持管理员追溯操作。</p></div></div><el-table :data="auditLogs" class="card"><el-table-column prop="createdAt" label="时间"/><el-table-column prop="userId" label="操作人ID"/><el-table-column prop="action" label="动作"/><el-table-column prop="resourceType" label="资源"/><el-table-column prop="resourceId" label="资源ID"/></el-table><section v-if="!auditLogs.length" class="card empty"><el-icon size="36"><Setting/></el-icon><p>暂无审计记录</p></section></template>
  <template v-else-if="page==='training'"><div class="page-head"><div><h1>培训学习</h1><p>进入已关联的 Moodle 课程，完成产品知识与售前能力学习。</p></div></div><div class="catalog-grid"><article v-for="course in courses" :key="course.id" class="card product-card"><div class="product-icon"><el-icon><Reading/></el-icon></div><h3>{{course.name}}</h3><p>{{course.summary}}</p><el-button type="primary" tag="a" :href="course.launchUrl" target="_blank" rel="noopener">进入课程</el-button></article></div><section v-if="!courses.length" class="card empty"><el-icon size="36"><Reading/></el-icon><p>暂无已发布课程</p></section></template>
 </div></section></main>
 <el-dialog v-model="productDialog" :title="editingProductId?'编辑产品':'新增产品'" width="520px"><el-form label-position="top"><el-form-item label="产品名称" required><el-input v-model="productForm.name"/></el-form-item><el-form-item label="产品型号" required><el-input v-model="productForm.model_code" :disabled="!!editingProductId"/></el-form-item><el-form-item label="产品分类" required><el-select v-model="productForm.category_id" style="width:100%" :disabled="!!editingProductId"><el-option v-for="c in productCategories" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item><el-form-item label="产品简介"><el-input v-model="productForm.summary" type="textarea" :rows="4"/></el-form-item><el-form-item label="销售状态"><el-select v-model="productForm.status" style="width:100%"><el-option label="在售" value="ON_SALE"/><el-option label="停售" value="OFF_SALE"/></el-select></el-form-item></el-form><template #footer><el-button @click="productDialog=false">取消</el-button><el-button type="primary" :loading="productSaving" @click="saveProduct">保存</el-button></template></el-dialog>
 <el-dialog v-model="catalogDialog" :title="editingCatalogId?'编辑知识条目':'新增知识条目'" width="520px"><el-form label-position="top"><el-form-item label="名称" required><el-input v-model="catalogForm.name"/></el-form-item><el-form-item v-if="['software','algorithms'].includes(page)" label="版本"><el-input v-model="catalogForm.version"/></el-form-item><el-form-item v-if="['algorithms','model-capabilities'].includes(page)" label="分类"><el-input v-model="catalogForm.category"/></el-form-item><el-form-item v-if="page==='solutions'" label="关联场景" required><el-select v-model="catalogForm.scene_id" style="width:100%"><el-option v-for="s in sceneOptions" :key="s.id" :label="s.name" :value="s.id"/></el-select></el-form-item><el-form-item v-if="page==='solutions'" label="方案等级"><el-input v-model="catalogForm.tier"/></el-form-item><el-form-item label="说明"><el-input v-model="catalogForm.summary" type="textarea" :rows="4"/></el-form-item></el-form><template #footer><el-button @click="catalogDialog=false">取消</el-button><el-button type="primary" :loading="catalogSaving" @click="saveCatalog">保存</el-button></template></el-dialog>
 <el-dialog v-model="projectDialog" title="保存项目配单" width="520px"><el-form label-position="top"><el-form-item label="项目名称" required><el-input v-model="projectForm.name"/></el-form-item><el-form-item label="客户" required><el-input v-model="projectForm.customer"/></el-form-item><el-form-item label="区域"><el-input v-model="projectForm.region"/></el-form-item><el-form-item label="应用场景" required><el-select v-model="projectForm.scene_id" style="width:100%"><el-option v-for="s in sceneOptions" :key="s.id" :label="s.name" :value="s.id"/></el-select></el-form-item></el-form><template #footer><el-button @click="projectDialog=false">取消</el-button><el-button type="primary" :loading="projectSaving" @click="saveProject">保存</el-button></template></el-dialog>
 <el-dialog v-model="projectDetail" title="项目配单详情" width="760px"><template v-if="projectDetail"><el-descriptions :column="2" border><el-descriptions-item label="项目">{{projectDetail.name}}</el-descriptions-item><el-descriptions-item label="客户">{{projectDetail.customer}}</el-descriptions-item><el-descriptions-item label="场景">{{projectDetail.scene}}</el-descriptions-item><el-descriptions-item label="版本">V{{projectDetail.bomVersion}}</el-descriptions-item></el-descriptions><el-table :data="projectDetail.bom" style="margin-top:16px"><el-table-column prop="name" label="产品"/><el-table-column prop="model" label="型号"/><el-table-column prop="quantity" label="数量"/></el-table></template><template #footer><el-button type="danger" plain @click="deleteProject">删除项目</el-button><el-button @click="projectDetail=null">关闭</el-button></template></el-dialog>
 <el-dialog v-model="documentDialog" title="上传资料" width="560px"><el-form label-position="top"><el-form-item label="选择文件" required><input type="file" @change="chooseDocument"/></el-form-item><el-form-item label="关联产品"><el-select v-model="documentForm.product_id" clearable style="width:100%"><el-option v-for="p in products" :key="p.id" :label="p.name" :value="p.id"/></el-select></el-form-item><el-form-item label="关联场景"><el-select v-model="documentForm.scene_id" clearable style="width:100%"><el-option v-for="s in sceneOptions" :key="s.id" :label="s.name" :value="s.id"/></el-select></el-form-item><el-form-item v-if="can('TENDER_VIEW')" label="关联投标项目"><el-select v-model="documentForm.tender_id" clearable style="width:100%"><el-option v-for="t in tenders" :key="t.id" :label="t.name" :value="t.id"/></el-select></el-form-item></el-form><template #footer><el-button @click="documentDialog=false">取消</el-button><el-button type="primary" :loading="documentSaving" @click="uploadDocument">上传</el-button></template></el-dialog>
 <el-dialog v-model="tenderDialog" :title="editingTenderId?'编辑投标项目':'新建投标项目'" width="560px"><el-form label-position="top"><el-form-item label="项目名称" required><el-input v-model="tenderForm.name"/></el-form-item><el-form-item label="客户" required><el-input v-model="tenderForm.customer"/></el-form-item><el-form-item label="截止时间"><el-date-picker v-model="tenderForm.deadline" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" style="width:100%"/></el-form-item><el-form-item label="状态"><el-select v-model="tenderForm.status" style="width:100%"><el-option label="编制中" value="PREPARING"/><el-option label="已提交" value="SUBMITTED"/><el-option label="已结束" value="CLOSED"/></el-select></el-form-item><el-form-item label="项目摘要"><el-input v-model="tenderForm.summary" type="textarea" :rows="4"/></el-form-item></el-form><template #footer><el-button @click="tenderDialog=false">取消</el-button><el-button type="primary" :loading="tenderSaving" @click="saveTender">保存</el-button></template></el-dialog>
 <el-dialog v-model="tenderDetail" title="投标项目详情" width="720px"><template v-if="tenderDetail"><el-descriptions :column="2" border><el-descriptions-item label="项目">{{tenderDetail.name}}</el-descriptions-item><el-descriptions-item label="客户">{{tenderDetail.customer}}</el-descriptions-item><el-descriptions-item label="状态">{{tenderDetail.status}}</el-descriptions-item><el-descriptions-item label="截止时间">{{tenderDetail.deadline?new Date(tenderDetail.deadline).toLocaleString():'未设置'}}</el-descriptions-item><el-descriptions-item label="摘要" :span="2">{{tenderDetail.summary||'暂无摘要'}}</el-descriptions-item></el-descriptions><h3 style="margin-top:20px">关联资料</h3><el-table :data="tenderDetail.documents"><el-table-column prop="name" label="文件名称"/><el-table-column prop="mimeType" label="类型"/><el-table-column label="操作" width="90"><template #default="s"><el-button link type="primary" @click="downloadDocument(s.row)">下载</el-button></template></el-table-column></el-table></template><template #footer><el-button v-if="can('TENDER_EDIT')" type="danger" plain @click="deleteTender(tenderDetail)">删除项目</el-button><el-button @click="tenderDetail=null">关闭</el-button></template></el-dialog>
</template>
